import {
  defineCapability,
  type CapabilityGateInput,
  type ServiceCapabilityAudit,
} from '../service-capability-contract';

/**
 * Runtime/governance/operations lane of the canonical platform inventory.
 *
 * Only services with a bounded, versioned operator-outcome denominator appear in `AUDITS`.
 * The rest remain explicitly unaudited so the canonical projection renders “not audited”, never
 * an invented 0% or 100%. Existing LiteLLM and Presidio audits stay owned by the canonical legacy
 * registry here so each service has exactly one family owner.
 */

type CapabilitySpec = readonly [
  id: string,
  name: string,
  summary: string,
  uiHref: string,
  uiLabel: string,
  gap: string,
  gates: CapabilityGateInput,
];

interface AuditSpec {
  serviceId: string;
  serviceLabel: string;
  upstreamVersion: string;
  versionSource: string;
  denominatorSource: string;
  auditState?: ServiceCapabilityAudit['auditState'];
  auditStateEvidence?: string;
  summary: string;
  capabilities: readonly CapabilitySpec[];
}

function audit(spec: AuditSpec): ServiceCapabilityAudit {
  return {
    serviceId: spec.serviceId,
    serviceLabel: spec.serviceLabel,
    upstreamVersion: spec.upstreamVersion,
    versionSource: spec.versionSource,
    denominatorSource: spec.denominatorSource,
    auditedAt: '2026-07-20',
    auditState: spec.auditState ?? 'stale',
    auditStateEvidence:
      spec.auditState === 'current'
        ? null
        : (spec.auditStateEvidence ??
          'The configured version is known, but the fleet ledger does not record the live image digest.'),
    summary: spec.summary,
    items: spec.capabilities.map((capability) => defineCapability(...capability)),
  };
}

const FLEET_EVIDENCE =
  '../onprem-fleet-orchestration/deploy/onprem/SERVICE_MAP.md and SERVER_STATE.md, verified 2026-07-20';
const PRESIDIO_ROUTE = '/governance/guardrails/overview';
const ROUTER_ROUTE = '/runtime/models/routing';

export const RUNTIME_GOVERNANCE_OPERATIONS_AUDITS = [
  audit({
    serviceId: 'console',
    serviceLabel: 'Console',
    upstreamVersion: '61b86a720f725bbd6fdd40d0368e499e22c1bc2e',
    versionSource: `${FLEET_EVIDENCE} release stamp`,
    denominatorSource:
      'src/app/(console) route tree; src/lib/tenancy-policy.ts; src/lib/adapters contracts',
    auditStateEvidence:
      'The fleet verified this immutable release, but the current working release has moved beyond it and is not deployed.',
    summary:
      'Bounded first-party denominator: authenticated operator access, management routes, tenant isolation, and durable run dispatch. Self-restart remains host-owned.',
    capabilities: [
      [
        'authenticated-control-plane',
        'Authenticated tenant control plane',
        'Open the governed management Console with tenant-scoped data and actions.',
        '/operations',
        'Open operations',
        '',
        [
          'yes',
          'The immutable Console release provides session and service-account authorization.',
          'yes',
          'NextAuth, tenancy, authorization, and repository seams are wired.',
          'yes',
          'All canonical domains are reachable through URL-driven Console routes.',
          'yes',
          'The authenticated integration harness exercised bank and insurance tenant routes.',
        ],
      ],
      [
        'tenant-management',
        'Tenant-isolated management state',
        'Create and manage product entities without crossing organization boundaries.',
        '/governance/access',
        'Manage access',
        '',
        [
          'yes',
          'The first-party release includes tenant-owned repositories and authorization rules.',
          'yes',
          'Database, claims, and policy adapters enforce organization scope.',
          'yes',
          'Domain management routes expose tenant-scoped entities and actions.',
          'yes',
          'Bank and insurance seed checks proved isolation of solution records.',
        ],
      ],
      [
        'self-lifecycle',
        'Console process lifecycle',
        'Deploy, restart, and roll back the control plane safely.',
        '/operations/admin',
        'Inspect administration',
        'Keep process lifecycle in the private deployment runbook; expose immutable build and rollback evidence without adding an unsafe self-restart action.',
        [
          'yes',
          'The release has native start, stop, deploy, and rollback runbooks.',
          'partial',
          'Deployment scripts own lifecycle; the running process does not control itself.',
          'partial',
          'Administration explains host ownership but does not execute deployment lifecycle.',
          'yes',
          'The fleet ledger records an immutable release and prepared rollback source.',
        ],
      ],
    ],
  }),
  audit({
    serviceId: 'gateway',
    serviceLabel: 'AI Gateway',
    upstreamVersion: 'Console release 61b86a720f725bbd6fdd40d0368e499e22c1bc2e',
    versionSource: `${FLEET_EVIDENCE}; packages/gateway and scripts/gateway-aggregator.mjs`,
    denominatorSource:
      'packages/gateway/src/index.ts; packages/gateway/src/cluster/types.ts; packages/gateway/src/queue/types.ts',
    auditStateEvidence:
      'The fleet verified this first-party gateway release, but the current working release is newer and not deployed.',
    summary:
      'Bounded first-party denominator: authenticated inference, model discovery, fleet routing, and request governance. Direct backend access is not part of the operator contract.',
    capabilities: [
      [
        'authenticated-inference',
        'Authenticated inference',
        'Run OpenAI-compatible inference through the governed on-prem door.',
        '/runtime/gateways',
        'Inspect gateways',
        '',
        [
          'yes',
          'The first-party gateway supports authenticated OpenAI-compatible inference.',
          'yes',
          'src/lib/gateway.ts and the inference adapter call the real gateway with service credentials.',
          'yes',
          'Runtime gateway and model surfaces expose the governed endpoint.',
          'yes',
          'The fleet gate proved a real completion and invalid-bearer rejection.',
        ],
      ],
      [
        'fleet-routing',
        'Fleet model routing',
        'Discover healthy models and route requests across active fleet nodes.',
        '/runtime/models',
        'Manage models',
        '',
        [
          'yes',
          'The gateway aggregator release provides pool membership, health, and routing.',
          'yes',
          'Gateway control and model-catalog adapters consume the real pool.',
          'yes',
          'Models, gateways, nodes, and clusters expose the routing relationship.',
          'yes',
          'The eight-node registry and Qwen/Gemma/Qwythos completions were verified.',
        ],
      ],
      [
        'request-governance',
        'Request policy and guardrail spine',
        'Apply tenancy, policy, guardrails, routing, and audit to inference requests.',
        '/governance/posture',
        'Inspect governance posture',
        '',
        [
          'yes',
          'The first-party gateway release supports the Off Grid governance contract.',
          'yes',
          'Policy, guardrail, credential, traffic, and audit adapters are wired.',
          'yes',
          'Governance and runtime surfaces expose effective controls and evidence.',
          'yes',
          'Governed denial and merged guard scans passed in the recovery gate.',
        ],
      ],
    ],
  }),
  audit({
    serviceId: 'keycloak',
    serviceLabel: 'Identity & SSO',
    upstreamVersion: '26.0.7',
    versionSource: 'deploy/docker-compose.yml (quay.io/keycloak/keycloak:26.0.7)',
    denominatorSource: 'https://www.keycloak.org/docs/26.0.7/server_admin/',
    summary:
      'Relevant denominator: human SSO, service accounts, tenant access, session/revocation controls, and identity lifecycle. Full realm administration is intentionally abstracted.',
    capabilities: [
      [
        'human-sso',
        'Human SSO and sessions',
        'Authenticate operators through the configured enterprise identity provider.',
        '/governance/access',
        'Manage access',
        'Prove the production Keycloak provider, logout, revocation, and session-expiry lifecycle; authenticated access alone is not the full lifecycle.',
        [
          'yes',
          'Keycloak 26.0.7 provides OIDC realms, clients, and user sessions.',
          'partial',
          'NextAuth has Keycloak support, but production-provider lifecycle evidence is incomplete.',
          'yes',
          'Access and team surfaces manage product membership and roles.',
          'partial',
          'Authenticated tenant sessions passed; logout/revocation/expiry were not re-verified.',
        ],
      ],
      [
        'service-accounts',
        'Service-account grants',
        'Issue client-credential grants to internal service adapters without hard-coded bearer tokens.',
        '/governance/access',
        'Inspect service access',
        'Expose the bounded client lifecycle and revocation posture without recreating raw realm administration.',
        [
          'yes',
          'Keycloak supports confidential clients and client-credential grants.',
          'yes',
          'The service credential broker exchanges OpenBao-held client secrets for grants.',
          'partial',
          'Access surfaces show product access; full client lifecycle is not a dedicated UI.',
          'yes',
          'Five client-credential grants passed in the fleet recovery evidence.',
        ],
      ],
      [
        'federation-mfa',
        'Federation and MFA policy',
        'Federate workforce identity and require suitable authentication assurance.',
        '/governance/access',
        'Manage access',
        'Audit the configured identity-provider and authentication-flow contracts, then expose assurance and recovery state without recreating raw Keycloak administration.',
        [
          'yes',
          'Keycloak 26.0.7 supports identity brokering and configurable authentication flows.',
          'no',
          'No production federation/MFA adapter contract is evidenced.',
          'no',
          'The Console does not expose federation or MFA posture.',
          'no',
          'No seeded bank or insurance identity-assurance workflow is verified.',
        ],
      ],
    ],
  }),
  audit({
    serviceId: 'temporal',
    serviceLabel: 'Durable Workflows',
    upstreamVersion: 'Temporal Server 1.25.2 / UI 2.32.0',
    versionSource: 'deploy/docker-compose.yml',
    denominatorSource: 'https://docs.temporal.io/',
    summary:
      'Relevant denominator: durable app/agent/chat dispatch, run lifecycle, schedules, retries, visibility, cancellation, and worker readiness.',
    capabilities: [
      [
        'durable-dispatch',
        'Durable app, agent, and chat dispatch',
        'Submit governed work to durable task queues and preserve run history.',
        '/operations/runs',
        'Inspect runs',
        '',
        [
          'yes',
          'Temporal 1.25.2 provides durable workflows, activities, histories, and task queues.',
          'yes',
          'App, agent, chat, schedule, and visibility adapters use Temporal clients and workers.',
          'yes',
          'Operations runs and app/agent run detail pages expose durable state.',
          'yes',
          'The fleet gate proved the Console durable-run surface and a durable denial path.',
        ],
      ],
      [
        'run-actions',
        'Run cancellation, retry, and replay',
        'Intervene in a failed or long-running workflow without losing audit history.',
        '/operations/runs',
        'Manage runs',
        'Verify each action against the deployed service and preserve user-visible action evidence.',
        [
          'yes',
          'Temporal supports termination, cancellation, reset/replay, and retry semantics.',
          'partial',
          'Run adapters expose bounded actions; the complete action matrix is not re-audited.',
          'partial',
          'Run detail surfaces expose actions, but complete live action evidence is absent.',
          'no',
          'No immutable cancellation/retry/replay workflow evidence is recorded.',
        ],
      ],
      [
        'worker-readiness',
        'Worker and task-queue readiness',
        'Know whether app, agent, and chat queues have compatible pollers before accepting work.',
        '/operations/services',
        'Inspect workers',
        'Expose task-queue compatibility, poller identity, queue lag, and drain state for each worker.',
        [
          'yes',
          'Temporal exposes task-queue pollers and worker build/versioning primitives.',
          'partial',
          'Indirect worker readiness is inferred from run state rather than a complete readiness contract.',
          'partial',
          'Workers appear in the service directory without queue depth or poller detail.',
          'partial',
          'Runs succeeded, but each worker queue was not independently proven.',
        ],
      ],
    ],
  }),
  audit({
    serviceId: 'app-worker',
    serviceLabel: 'App Worker',
    upstreamVersion:
      'First-party source 21bd2f1ab450a531c031df6167dd3aee2a800971 / @temporalio/worker 1.20.2',
    versionSource:
      'Console git snapshot 21bd2f1ab450a531c031df6167dd3aee2a800971; package-lock.json; onprem-fleet-orchestration launch manifest 3e91d5d357e824dabfe6a97a3bc0015b897c37c6',
    denominatorSource:
      'scripts/app-worker.mts; src/lib/app-run-durable.ts; src/lib/adapters/apprun.ts; src/worker/app-run.workflow.ts; src/worker/app-run.activities.ts; src/lib/app-run.ts; src/lib/app-run-resume.ts; src/lib/app-run-store.ts',
    auditState: 'current',
    summary:
      'Pinned first-party denominator: worker artifact identity, queue readiness, governed step execution, durable human review, failure recovery, and output persistence. Code-path evidence is kept separate from live worker proof.',
    capabilities: [
      [
        'artifact-identity',
        'Immutable worker artifact identity',
        'Identify the exact app-worker source, runtime dependency, launch contract, and deployed artifact before assigning work.',
        '/operations/services/app-worker',
        'Inspect app worker',
        'Build and publish a worker-specific immutable artifact stamp, then correlate its checksum and launch-manifest revision with the live poller and service inventory.',
        [
          'yes',
          'The first-party worker source, Temporal Worker SDK 1.20.2, and launch-manifest revision are pinned independently.',
          'partial',
          'The launch manifest starts scripts/app-worker.mts from a checkout; it does not bind a built artifact checksum to the running poller.',
          'no',
          'The service detail does not expose the worker source SHA, manifest revision, or runtime artifact checksum.',
          'no',
          'No retained production app run is correlated to an immutable app-worker artifact identity.',
        ],
      ],
      [
        'task-queue-readiness',
        'Task queue and poller readiness',
        'Confirm a compatible app worker is polling offgrid-apps before durable work is accepted.',
        '/operations/services/app-worker',
        'Inspect app worker',
        'Add app-worker-specific poller identity, queue lag, compatibility, heartbeat, and drain-state probes; do not infer readiness from Temporal availability or an eventual run state.',
        [
          'yes',
          'scripts/app-worker.mts creates a Temporal Worker on the configured queue and fails startup when required runtime configuration is invalid.',
          'partial',
          'Queue selection and launch supervision exist, but no app-worker-specific poller, lag, heartbeat, compatibility, or drain reader is wired into readiness.',
          'partial',
          'The generic service detail can show the worker entry, but it cannot prove an offgrid-apps poller is compatible and draining work.',
          'no',
          'No retained live evidence independently proves the offgrid-apps task queue has an active compatible poller.',
        ],
      ],
      [
        'governed-step-execution',
        'Governed step execution',
        'Execute app steps with tenant, actor, pipeline, policy, guardrail, routing, and provenance context intact.',
        '/solutions/apps',
        'Manage apps',
        'Retain a correlated bank or insurance production run proving the app-worker—not an inline fallback—executed each governed step under the selected pipeline contract.',
        [
          'yes',
          'The pinned worker implements read-data, connector, agent, guardrail, human, and output step contracts.',
          'yes',
          'executeStepActivity re-resolves the app and pipeline binding at execution time and reuses the production governed step executor with organization and actor context.',
          'yes',
          'App build, run, review, report, and operations-run routes expose the complete operator journey.',
          'no',
          'Focused integration tests prove the real executor seam, but no retained fleet evidence attributes a BFSI app run to this worker artifact.',
        ],
      ],
      [
        'human-pause-resume',
        'Durable human pause and resume',
        'Pause a multi-step app at an authority gate, preserve history, and resume or reject it through an audited decision.',
        '/solutions/reviews',
        'Open review queue',
        'Prove a live offgrid-apps workflow through pause, authorized approval or rejection, resume, and final evidence; include worker attribution and reject unauthorized or duplicate decisions.',
        [
          'yes',
          'The workflow waits durably on a review signal and models approval, rejection, and edited output.',
          'yes',
          'The review API signals Temporal first, preserves paused state when the service is unreachable, and uses the inline resume adapter only when durable execution is not configured or not found.',
          'yes',
          'The review queue and run detail routes expose the pending decision and permitted action.',
          'no',
          'No retained production app-worker run proves pause, approval or rejection, durable resume, and final completion end to end.',
        ],
      ],
      [
        'failure-recovery',
        'Failure and restart recovery',
        'Retry transient step failures and survive worker loss without duplicating side effects or losing the operator-visible run.',
        '/operations/runs',
        'Inspect durable runs',
        'Add worker build/version compatibility and safe drain controls, then prove interruption, restart, retry exhaustion, idempotency, and recovery against a live governed app run.',
        [
          'yes',
          'Temporal histories, bounded activity retries, deterministic workflow IDs, and launchd KeepAlive provide the required recovery primitives.',
          'partial',
          'The workflow has retry policy and deterministic dispatch, but the worker lacks build compatibility, safe drain, and a verified side-effect idempotency contract for every step.',
          'partial',
          'Run detail exposes failure state and actions, but app-worker drain, poller compatibility, and restart recovery are not operator-visible.',
          'no',
          'No retained live workflow proves an interrupted app-worker run safely resumes after process restart.',
        ],
      ],
      [
        'output-persistence',
        'Output and run-state persistence',
        'Persist step state, final output, report artifacts, and provenance so an operator can inspect and act on the result later.',
        '/operations/runs',
        'Inspect run outputs',
        'Stop swallowing app-run persistence failures or add a replayable reconciliation path from Temporal history; then prove a completed output, report artifact, and provenance record survive a database interruption.',
        [
          'yes',
          'The app runtime defines app_runs persistence, aggregate output, signed report artifacts, and Temporal workflow history.',
          'partial',
          'The worker persists state around transitions, but persistState intentionally swallows database errors and has no replay or backfill repair path.',
          'yes',
          'App and operations run detail/report routes expose persisted status, output, and artifacts when writes succeed.',
          'no',
          'No retained production evidence correlates a worker-completed output, database row, signed artifact, and provenance record or proves recovery after a missed write.',
        ],
      ],
    ],
  }),
  audit({
    serviceId: 'opa',
    serviceLabel: 'Policy Engine',
    upstreamVersion: '0.70.0',
    versionSource: 'deploy/docker-compose.yml (openpolicyagent/opa:0.70.0)',
    denominatorSource: 'https://www.openpolicyagent.org/docs/v0.70.0/',
    summary:
      'Relevant denominator: policy/module/data lifecycle, decision evaluation, bundles, decision logs, and failure posture. Rego stays behind governed product modules.',
    capabilities: [
      [
        'policy-decisions',
        'Governed policy decisions',
        'Evaluate tenant-scoped allow/deny decisions and preserve explainable evidence.',
        '/governance/policies/decisions',
        'Inspect decisions',
        '',
        [
          'yes',
          'OPA 0.70.0 provides policy evaluation and decision APIs.',
          'yes',
          'The policy adapter evaluates real requests and records decisions.',
          'yes',
          'Policies and evidence routes expose rules and decisions.',
          'yes',
          'The fleet gate proved a governed denial.',
        ],
      ],
      [
        'policy-lifecycle',
        'Policy and module lifecycle',
        'Create, edit, publish, version, and retire governed policy rules.',
        '/governance/policies/rules',
        'Manage rules',
        'Prove publish/reload and rollback against deployed OPA, including invalid-policy failure behavior.',
        [
          'yes',
          'OPA provides policy and data document APIs.',
          'partial',
          'Console policy rules/modules exist; complete deployed reload and rollback evidence is missing.',
          'yes',
          'Rules, templates, modules, and decisions have canonical nested routes.',
          'partial',
          'Seeded policies exist, but publish/reload/rollback were not all live-proven.',
        ],
      ],
      [
        'bundles-decision-logs',
        'Bundles and decision-log export',
        'Distribute policy safely and export complete decision telemetry.',
        '/governance/evidence/audit',
        'Inspect audit evidence',
        'Wire bundle activation and decision-log export through managed adapters, then prove rollback and loss handling.',
        [
          'yes',
          'OPA 0.70.0 supports bundles and decision-log plugins.',
          'no',
          'No managed bundle or OPA decision-log plugin adapter is evidenced.',
          'partial',
          'Off Grid audit decisions are visible, but OPA bundle/log lifecycle is not.',
          'no',
          'No bundle rollout or decision-log export workflow is verified.',
        ],
      ],
    ],
  }),
  audit({
    serviceId: 'openbao',
    serviceLabel: 'Secrets Vault',
    upstreamVersion: '2.1.0',
    versionSource: 'deploy/docker-compose.yml (openbao/openbao:2.1.0)',
    denominatorSource: 'https://openbao.org/docs/2.1.x/',
    summary:
      'Relevant denominator: secret CRUD, connector and service credentials, leases, mounts, rotation, auth, policy, audit, and recovery. Root administration is excluded.',
    capabilities: [
      [
        'secret-lifecycle',
        'Tenant secret lifecycle',
        'Create, read, update, and delete governed secrets without revealing values in client state.',
        '/governance/secrets/keys',
        'Manage keys',
        '',
        [
          'yes',
          'OpenBao 2.1.0 provides versioned KV secret lifecycle APIs.',
          'yes',
          'The secrets adapter and connector-secret seam perform server-side lifecycle operations.',
          'yes',
          'Keys and connector forms expose product-owned secret operations.',
          'yes',
          'A connector vault round-trip and five service-secret reads passed.',
        ],
      ],
      [
        'dynamic-credentials',
        'Dynamic database credentials and leases',
        'Issue short-lived credentials, inspect leases, and revoke access.',
        '/governance/secrets/dynamic-database',
        'Manage dynamic credentials',
        'Prove database engine configuration, issue/renew/revoke, and expiry in the live fleet.',
        [
          'yes',
          'OpenBao 2.1.0 provides database secrets and lease APIs.',
          'partial',
          'Dynamic credential models and routes exist; full live engine lifecycle is unverified.',
          'yes',
          'Dynamic database and lease routes are deep-linkable.',
          'no',
          'No immutable issue/renew/revoke workflow is in the fleet ledger.',
        ],
      ],
      [
        'vault-recovery',
        'Vault audit and disaster recovery',
        'Back up encrypted state, inspect audit devices, and recover without credential loss.',
        '/operations/backups',
        'Manage backups',
        'Add and verify OpenBao backup/restore plus audit-device evidence; a mounted volume alone is not recovery proof.',
        [
          'yes',
          'OpenBao supports file-backed storage, audit devices, and operational recovery procedures.',
          'partial',
          'The persistent volume is declared; complete backup/restore and audit adapters are absent.',
          'partial',
          'Backup and evidence surfaces do not expose a full vault recovery drill.',
          'no',
          'No OpenBao restore drill is recorded.',
        ],
      ],
    ],
  }),
  audit({
    serviceId: 'unleash',
    serviceLabel: 'Feature Flags',
    upstreamVersion: '6.6 mutable minor tag',
    versionSource: 'deploy/docker-compose.yml (unleashorg/unleash-server:6.6)',
    denominatorSource: 'https://docs.getunleash.io/reference',
    auditStateEvidence:
      'The configured 6.6 tag is not digest-pinned; the live immutable upstream version is unknown.',
    summary:
      'Relevant denominator: flag CRUD, enablement, rollout strategies, variants, environment state, and audited product use. The mutable tag prevents a current availability claim.',
    capabilities: [
      [
        'flag-lifecycle',
        'Feature-flag lifecycle',
        'Create, describe, enable, disable, and archive product flags.',
        '/operations/configuration',
        'Manage configuration',
        'Pin the live image and prove create-to-archive through the operator UI.',
        [
          'yes',
          'Unleash 6.6 documentation describes feature CRUD and environment enablement.',
          'yes',
          'Admin adapters implement create, description update, toggle, and archive.',
          'partial',
          'Configuration consumes flags; complete lifecycle discoverability is not live-proven.',
          'no',
          'No seeded end-to-end flag lifecycle is recorded.',
        ],
      ],
      [
        'progressive-rollout',
        'Progressive rollout and variants',
        'Roll out a capability gradually and choose controlled variants.',
        '/operations/configuration',
        'Manage rollouts',
        'Prove a tenant-scoped percentage rollout and variant changes real product behavior.',
        [
          'yes',
          'Unleash 6.6 provides strategies and variants.',
          'yes',
          'Adapters implement rollout percentages and variant payloads.',
          'partial',
          'No dedicated rollout/variant journey is evidenced in the Console.',
          'no',
          'No bank or insurance workflow is verified under a rollout.',
        ],
      ],
    ],
  }),
  audit({
    serviceId: 'redis',
    serviceLabel: 'Redis',
    upstreamVersion: '7.4 mutable alpine tag',
    versionSource: 'deploy/docker-compose.yml (redis:7.4-alpine)',
    denominatorSource: 'https://redis.io/docs/latest/develop/',
    auditStateEvidence:
      'The configured 7.4-alpine tag is not digest-pinned and live backend selection is not recorded.',
    summary:
      'Relevant denominator: shared response-cache get/set/expiry/invalidation, backend health, and graceful fallback. Redis remains an implementation behind the cache port.',
    capabilities: [
      [
        'shared-response-cache',
        'Shared response cache',
        'Cache governed responses across Console processes with bounded expiry.',
        '/operations/services/redis',
        'Inspect Redis',
        'Prove the deployed runtime selects Redis and expose hit, miss, expiry, and invalidation evidence.',
        [
          'yes',
          'Redis 7.4 provides key/value storage and expiry.',
          'partial',
          'The cache port supports Redis, but the running backend is not identified in evidence.',
          'partial',
          'Service detail exposes health, not cache operations or metrics.',
          'no',
          'No production request trace proves a Redis hit or invalidation.',
        ],
      ],
      [
        'failure-fallback',
        'Cache failure fallback',
        'Continue safely on an in-process cache when Redis is unavailable.',
        '/operations/health',
        'Inspect health',
        'Prove failover and recovery under a real connection loss without hiding stale data.',
        [
          'yes',
          'The Off Grid cache contract defines an in-process fallback.',
          'yes',
          'The Redis adapter degrades to the in-process implementation.',
          'partial',
          'Health labels the fallback; operators cannot inspect transition history.',
          'no',
          'No deployed failover/recovery workflow is recorded.',
        ],
      ],
    ],
  }),
  audit({
    serviceId: 'superset',
    serviceLabel: 'BI & Dashboards',
    upstreamVersion: '4.1.1',
    versionSource: 'deploy/docker-compose.yml (apache/superset:4.1.1)',
    denominatorSource: 'https://superset.apache.org/docs/6.0.0/intro',
    summary:
      'Relevant operator denominator: governed dashboard provisioning, native chart read-back, embedded access, and bounded authoring. Superset remains the query engine; the Console owns the operator experience.',
    capabilities: [
      [
        'dashboard-provisioning',
        'Governed dashboard provisioning',
        'Idempotently create the Off Grid database, dataset, charts, and dashboard.',
        '/insights/usage/dashboards',
        'Manage dashboards',
        '',
        [
          'yes',
          'Superset 4.1.1 provides database, dataset, chart, dashboard, and embedded-config APIs.',
          'yes',
          'src/lib/superset.ts authenticates and performs idempotent find-or-create provisioning.',
          'yes',
          'Insights > Usage > Dashboards is the canonical governed dashboard route.',
          'yes',
          'The fleet ledger records dashboard 1 and charts 1 and 2 provisioned through the Console API.',
        ],
      ],
      [
        'native-chart-readback',
        'Native governed chart read-back',
        'Run Superset chart queries and render the results inside the Off Grid visual system.',
        '/insights/usage/dashboards',
        'View dashboards',
        '',
        [
          'yes',
          'Superset 4.1.1 provides chart-data APIs.',
          'yes',
          'src/lib/superset-data.ts resolves owned charts, runs chart-data queries, and shapes results.',
          'yes',
          'The Console renders the governed dashboard in its native Insights surface.',
          'yes',
          'The provisioned request and token charts query the live Console database.',
        ],
      ],
      [
        'embedded-access',
        'Scoped embedded dashboard access',
        'Mint short-lived guest access only after verifying the owned dashboard exists.',
        '/insights/usage/dashboards',
        'Open governed dashboard',
        'Capture one immutable guest-token and expiry/revocation workflow; configured code alone is not production proof.',
        [
          'yes',
          'Superset 4.1.1 supports embedded dashboard configuration and guest tokens.',
          'yes',
          'The Superset adapter verifies the dashboard before minting a scoped guest token.',
          'yes',
          'The dashboard route can open the governed embedded resource.',
          'partial',
          'Dashboard provisioning is proven, but guest-token expiry and revocation are not in fleet evidence.',
        ],
      ],
      [
        'sql-authoring',
        'Advanced SQL and chart authoring',
        'Let authorized analysts explore governed data and publish additional visualizations.',
        '/insights/usage/dashboards',
        'Open dashboard tools',
        'Define the analyst authorization boundary and either integrate bounded authoring or explicitly keep it in the separately authenticated Superset surface.',
        [
          'yes',
          'Superset 4.1.1 provides SQL Lab, datasets, charts, and dashboards.',
          'partial',
          'The Console provisions its owned assets but does not wrap the full authoring lifecycle.',
          'partial',
          'Operators can link to Superset; authoring is not a native Off Grid CRUD surface.',
          'no',
          'No seeded analyst authoring workflow is verified.',
        ],
      ],
    ],
  }),
  audit({
    serviceId: 'fleetdm',
    serviceLabel: 'Device Management',
    upstreamVersion: '4.87.0',
    versionSource: 'deploy/docker-compose.yml (fleetdm/fleet:v4.87.0)',
    denominatorSource: 'https://fleetdm.com/docs/rest-api/rest-api',
    summary:
      'Relevant Community-edition denominator: host inventory, live/saved queries, software/CVE visibility, and policies. Premium MDM control is explicitly unsupported without licensing.',
    capabilities: [
      [
        'host-inventory-software',
        'Host and software inventory',
        'Inspect enrolled devices, installed software, and vulnerability context.',
        '/operations/devices',
        'Manage devices',
        'Complete operator setup, enroll a real test host, and prove inventory refresh.',
        [
          'yes',
          'Fleet 4.87.0 Community provides host and software inventory.',
          'yes',
          'Fleet adapters map hosts and software inventory.',
          'yes',
          'Operations device list and detail routes expose inventory.',
          'no',
          'The live fleet has no operator-owned enrollment evidence.',
        ],
      ],
      [
        'queries-policies',
        'Live queries and compliance policies',
        'Run bounded osquery queries and manage host compliance checks.',
        '/operations/devices',
        'Manage device posture',
        'Prove one safe query and one policy lifecycle against an enrolled live host.',
        [
          'yes',
          'Fleet 4.87.0 Community provides queries, campaigns, and policies.',
          'yes',
          'Adapters and routes implement live query and policy CRUD.',
          'yes',
          'Device surfaces expose query and policy actions.',
          'no',
          'No enrolled-host query or policy evidence is recorded.',
        ],
      ],
      [
        'premium-mdm',
        'Premium device control',
        'Lock, wipe, and push configuration profiles to managed devices.',
        '/operations/devices',
        'Inspect device controls',
        'Keep these controls unavailable until a compatible Fleet Premium license, server capability, enrollment, and live safety proof exist.',
        [
          'no',
          'The deployed Community configuration does not establish Premium MDM availability.',
          'partial',
          'Adapters model commands but gate unavailable controls.',
          'partial',
          'The UI can explain unavailability without presenting a working control.',
          'no',
          'No device-control workflow is verified.',
        ],
      ],
    ],
  }),
  {
    serviceId: 'presidio',
    serviceLabel: 'Presidio',
    upstreamVersion: '2.2.356',
    versionSource: 'deploy/docker-compose.yml',
    denominatorSource: 'https://microsoft.github.io/presidio/api-docs/',
    auditedAt: '2026-07-19',
    auditState: 'current',
    auditStateEvidence: null,
    summary:
      'Text analysis, replacement anonymization, org recognizers, deny lists, and thresholds are integrated into the data-redaction path. Language and advanced anonymizer operations remain narrow.',
    items: [
      defineCapability(
        'text-analysis',
        'Text entity analysis',
        'Detect built-in PII entities and return typed spans with confidence scores.',
        '/governance/guardrails/test',
        'Test live detection',
        '',
        [
          'yes',
          'The analyzer image exposes /analyze.',
          'yes',
          'scanWithPresidio posts a typed analyze request and applies returned spans.',
          'yes',
          'The Guardrails test surface runs the active engine.',
          'yes',
          'The selected data-redaction adapter runs in app and data-movement policy checks.',
        ],
      ),
      defineCapability(
        'replace-anonymization',
        'Replacement anonymization',
        'Send analyzed spans to the anonymizer and replace values with entity markers.',
        '/governance/guardrails/test',
        'Test live redaction',
        '',
        [
          'yes',
          'The anonymizer image exposes /anonymize with replace operators.',
          'yes',
          'The adapter calls analyzer then anonymizer and has a span-safe local fallback.',
          'yes',
          'The test surface displays the redacted result and active engine.',
          'yes',
          'Data-redaction workflows consume the returned redacted text.',
        ],
      ),
      defineCapability(
        'pattern-recognizers',
        'Custom pattern recognizers',
        'Create org-scoped regex and context recognizers and send them per analyze request.',
        '/governance/guardrails/recognizers',
        'Manage recognizers',
        '',
        [
          'yes',
          'Presidio accepts ad_hoc_recognizers with regex patterns and context.',
          'yes',
          'Stored recognizers are normalized and merged into every analyze request.',
          'yes',
          'The recognizers route provides create, update, enable, and delete controls.',
          'yes',
          'The same org policy is loaded by the real data-redaction adapter.',
        ],
      ),
      defineCapability(
        'deny-lists',
        'Custom deny lists',
        'Flag fixed org-specific terms as a named PII entity.',
        '/governance/guardrails/recognizers',
        'Manage deny lists',
        '',
        [
          'yes',
          'PatternRecognizer supports deny_list values.',
          'yes',
          'Deny lists are translated into enabled ad hoc recognizers.',
          'yes',
          'The recognizer manager supports deny-list CRUD.',
          'yes',
          'Enabled deny lists are loaded into production analyze requests.',
        ],
      ),
      defineCapability(
        'confidence-thresholds',
        'Global and per-entity thresholds',
        'Set an org floor and stricter or looser thresholds by entity type.',
        '/governance/guardrails/thresholds',
        'Manage thresholds',
        '',
        [
          'yes',
          'The analyzer accepts a request score threshold.',
          'yes',
          'The global floor is sent upstream and per-entity thresholds are enforced on returned scores.',
          'yes',
          'The thresholds route edits the org policy.',
          'yes',
          'The real adapter loads and applies the org threshold policy.',
        ],
      ),
      defineCapability(
        'languages',
        'Language selection and multilingual analysis',
        'Choose a supported language and recognizer set for each analysis request.',
        PRESIDIO_ROUTE,
        'Inspect Presidio status',
        'The adapter has a language parameter but every production call defaults to en. Add supported-language discovery, validation, and an org or pipeline setting before advertising multilingual detection.',
        [
          'yes',
          'Presidio supports language-specific recognizers.',
          'partial',
          'The request builder accepts language, but the registered port never supplies a non-English value.',
          'no',
          'There is no language control on the Guardrails surface.',
          'no',
          'Production scans are fixed to English.',
        ],
      ),
      defineCapability(
        'advanced-anonymizers',
        'Mask, hash, encrypt, redact, and custom operators',
        'Apply an anonymizer operator per entity instead of fixed replacement markers.',
        '/governance/guardrails/masking',
        'Open masking policy',
        'The adapter hard-codes replace. Add a validated operator policy, secret-backed encryption keys, reversible-data handling, and UI controls before exposing advanced operators.',
        [
          'yes',
          'Presidio anonymizer ships multiple operator types.',
          'partial',
          'The analyzer-to-anonymizer flow is wired, but only replace is constructed.',
          'no',
          'Masking rules do not configure Presidio anonymizer operators.',
          'no',
          'No production workflow selects a non-replace operator.',
        ],
      ),
      defineCapability(
        'image-redaction',
        'Image PII redaction',
        'Detect and redact PII in images and scanned documents.',
        PRESIDIO_ROUTE,
        'Inspect Presidio status',
        'The deployed analyzer/anonymizer pair has no image-redactor adapter, API route, or review UI.',
        [
          'yes',
          'Presidio provides an image redactor capability.',
          'no',
          'No image-redactor service or adapter is registered.',
          'no',
          'No image redaction UI exists.',
          'no',
          'No document or media workflow invokes Presidio image redaction.',
        ],
      ),
    ],
  },
  {
    serviceId: 'litellm',
    serviceLabel: 'LiteLLM',
    upstreamVersion: 'main-stable (mutable image tag)',
    versionSource: 'deploy/docker-compose.yml',
    denominatorSource: 'https://docs.litellm.ai/docs/',
    auditedAt: '2026-07-19',
    auditState: 'current',
    auditStateEvidence: null,
    summary:
      'The router config generator, management read-back, and inference endpoint seam are built. The live model-door cutover and callback delivery remain unverified, so routing and enforcement do not count as production use.',
    items: [
      defineCapability(
        'openai-proxy',
        'OpenAI-compatible inference proxy',
        'Serve chat and model requests through a single OpenAI-compatible model door.',
        ROUTER_ROUTE,
        'Inspect inference wiring',
        'The endpoint resolver can select LiteLLM, but the audited deployment has no verified live cutover. Run chat and governed pipeline traffic through the selected provider and record the serving deployment.',
        [
          'yes',
          'LiteLLM Proxy exposes OpenAI-compatible inference APIs.',
          'yes',
          'The gateway endpoint seam resolves LiteLLM URL and bearer credentials.',
          'yes',
          'The Routing view shows the selected inference door.',
          'partial',
          'Production request paths support the seam, but live LiteLLM cutover is not verified.',
        ],
      ),
      defineCapability(
        'load-balance-failover',
        'Load balancing, retries, and failover',
        'Route a model alias across fleet and cloud deployments with health-aware retry policy.',
        ROUTER_ROUTE,
        'Inspect routing health',
        'Generated config enables routing policy, but no live multi-node failure drill proves failover on the production model door.',
        [
          'yes',
          'LiteLLM Router supports deployment groups, health-aware balancing, retries, and fallbacks.',
          'yes',
          'The generated config defines model groups, retry policy, and deployment metadata.',
          'yes',
          'The Routing view displays deployment health.',
          'no',
          'No verified production cutover or failure drill exists.',
        ],
      ),
      defineCapability(
        'deployment-inventory',
        'Deployment inventory and health',
        'Read configured models and merge them with healthy and unhealthy endpoint state.',
        ROUTER_ROUTE,
        'Inspect deployments',
        '',
        [
          'yes',
          'LiteLLM exposes model info and health endpoints.',
          'yes',
          'safeRouterView merges /model/info and /health without fabricating missing deployments.',
          'yes',
          'The Routing view renders deployment, model, egress, vision, and health.',
          'yes',
          'Operations can inspect the configured LiteLLM service independently of model-door selection.',
        ],
      ),
      defineCapability(
        'budgets-rate-limits',
        'Budgets and RPM/TPM limits',
        'Enforce spend and request limits on virtual keys.',
        ROUTER_ROUTE,
        'Inspect key budget',
        'The adapter reads only the caller or master key snapshot and the UI is read-only. Add tenant-safe key selection, CRUD, enforced-limit verification, and audit records.',
        [
          'yes',
          'LiteLLM supports per-key budget, RPM, and TPM controls.',
          'partial',
          'The adapter reads one /key/info snapshot but does not create or update limits.',
          'partial',
          'The Routing view displays the returned budget and limits but cannot manage them.',
          'no',
          'No production request is verified to stop at a LiteLLM budget or rate limit.',
        ],
      ),
      defineCapability(
        'virtual-keys',
        'Virtual key lifecycle',
        'Create, rotate, revoke, scope, and inspect LiteLLM virtual keys.',
        ROUTER_ROUTE,
        'Inspect current key snapshot',
        'Only /key/info read-back exists. Add a credential-brokered lifecycle API and UI without exposing raw keys after creation.',
        [
          'yes',
          'LiteLLM exposes virtual key management APIs.',
          'partial',
          'The adapter can inspect one key but has no lifecycle operations.',
          'partial',
          'A budget snapshot is visible; key management is absent.',
          'no',
          'No business workflow provisions or revokes LiteLLM keys.',
        ],
      ),
      defineCapability(
        'provider-pools',
        'Fleet and cloud provider pools',
        'Generate deployment entries for on-prem nodes and approved cloud providers.',
        '/runtime/models/providers',
        'Inspect model providers',
        'The generator consumes fleet and environment inputs, but the console does not own a validated LiteLLM config publish or reload transaction.',
        [
          'yes',
          'LiteLLM supports many providers behind model aliases.',
          'yes',
          'buildLiteLLMConfig maps fleet nodes and cloud providers to model_list entries.',
          'partial',
          'Provider status is visible, but it is not a LiteLLM pool editor.',
          'no',
          'No production workflow publishes and reloads generated config through the console.',
        ],
      ),
      defineCapability(
        'structured-callbacks',
        'Structured request logging callbacks',
        'Send completion outcomes, deployment, tokens, caller, latency, and status into traffic records.',
        '/runtime/models/traffic',
        'Open model traffic',
        'The pure payload mapper exists, but the concrete callback receiver and OpenSearch writer are missing. The traffic UI is not proof that LiteLLM callbacks are flowing.',
        [
          'yes',
          'LiteLLM emits StandardLoggingPayload callbacks.',
          'partial',
          'litellmPayloadToTrafficRecord is implemented; no callback process invokes and persists it.',
          'partial',
          'Traffic and logs surfaces exist but do not identify a LiteLLM callback source.',
          'no',
          'No production LiteLLM callback reaches the traffic index.',
        ],
      ),
      defineCapability(
        'spend-analytics',
        'Spend and cost analytics',
        'Attribute request cost by key, model, deployment, team, and time window.',
        '/insights/cost',
        'Open cost insights',
        'The budget snapshot reports one spend total, while callback cost is deliberately not mapped into TrafficRecord. Add a canonical cost event and reconcile it with existing accounting.',
        [
          'yes',
          'LiteLLM calculates spend and exposes cost data.',
          'partial',
          'One key spend value is read; request-level cost is not persisted.',
          'partial',
          'Cost insights exist, but they are not fed by LiteLLM cost records.',
          'no',
          'No production accounting workflow consumes LiteLLM-attributed cost.',
        ],
      ),
      defineCapability(
        'response-cache',
        'Response caching',
        'Cache eligible model responses with explicit privacy, scope, and expiry policy.',
        ROUTER_ROUTE,
        'Inspect router capabilities',
        'No LiteLLM cache is configured or surfaced. Define tenant-safe cache keys, PII exclusions, retention, and purge controls before enabling it.',
        [
          'yes',
          'LiteLLM supports response cache backends.',
          'no',
          'The generated config has no cache section.',
          'no',
          'No LiteLLM cache state or controls exist.',
          'no',
          'No production request uses LiteLLM response caching.',
        ],
      ),
      defineCapability(
        'proxy-guardrails',
        'Proxy guardrails and policy hooks',
        'Run supported guardrails in the proxy before or after model calls.',
        ROUTER_ROUTE,
        'Inspect router capabilities',
        'Governance remains in the Off Grid pipeline spine. That is a valid ownership choice, but LiteLLM guardrail capability is not integrated and must not be counted.',
        [
          'yes',
          'LiteLLM supports proxy guardrail integrations.',
          'no',
          'No LiteLLM guardrail is configured or adapted.',
          'no',
          'The Router view has no proxy guardrail controls.',
          'no',
          'Production governance runs in the Off Grid policy and guardrail spine instead.',
        ],
      ),
    ],
  },
] as const satisfies readonly ServiceCapabilityAudit[];

/**
 * These services belong to this lane but still lack a versioned upstream denominator. Keeping the
 * IDs explicit proves inventory coverage while leaving the canonical capability summary honestly
 * `not-audited`.
 */
export const RUNTIME_GOVERNANCE_OPERATIONS_UNAUDITED_SERVICE_IDS = [
  'edge-gateway',
  'llm-guard',
  'gateway-control',
  'agent-worker',
  'chat-worker',
  'cloudflared',
  'landing',
  'status-page',
  'litellm-forwarder',
  'observability-forwarder',
  'fleet-forwarder',
] as const;

export const RUNTIME_GOVERNANCE_OPERATIONS_SERVICE_IDS = [
  ...RUNTIME_GOVERNANCE_OPERATIONS_AUDITS.map((record) => record.serviceId),
  ...RUNTIME_GOVERNANCE_OPERATIONS_UNAUDITED_SERVICE_IDS,
] as const;
