import {
  defineCapability,
  type CapabilityGateInput,
  type ServiceCapabilityAudit,
} from '../service-capability-contract';

/**
 * Runtime/governance/operations lane of the canonical platform inventory.
 *
 * Only services with a bounded, versioned operator-outcome denominator appear in `AUDITS`.
 * The rest remain explicitly unaudited so the canonical projection renders “not audited”, never
 * an invented 0% or 100%. Existing LiteLLM and Presidio audits stay owned by the canonical legacy
 * registry here so each service has exactly one family owner.
 */

type CapabilitySpec = readonly [
  id: string,
  name: string,
  summary: string,
  uiHref: string,
  uiLabel: string,
  gap: string,
  gates: CapabilityGateInput,
];

interface AuditSpec {
  serviceId: string;
  serviceLabel: string;
  upstreamVersion: string;
  versionSource: string;
  denominatorSource: string;
  auditState?: ServiceCapabilityAudit['auditState'];
  auditStateEvidence?: string;
  summary: string;
  capabilities: readonly CapabilitySpec[];
}

function audit(spec: AuditSpec): ServiceCapabilityAudit {
  return {
    serviceId: spec.serviceId,
    serviceLabel: spec.serviceLabel,
    upstreamVersion: spec.upstreamVersion,
    versionSource: spec.versionSource,
    denominatorSource: spec.denominatorSource,
    auditedAt: '2026-07-20',
    auditState: spec.auditState ?? 'stale',
    auditStateEvidence:
      spec.auditState === 'current'
        ? null
        : (spec.auditStateEvidence ??
          'The configured version is known, but the fleet ledger does not record the live image digest.'),
    summary: spec.summary,
    items: spec.capabilities.map((capability) => defineCapability(...capability)),
  };
}

const FLEET_EVIDENCE =
  '../onprem-fleet-orchestration/deploy/onprem/SERVICE_MAP.md and SERVER_STATE.md, verified 2026-07-20';
const PRESIDIO_ROUTE = '/governance/guardrails/overview';
const GUARDRAILS_ROUTE = '/governance/guardrails/overview';
const GUARDRAILS_PROTECTIONS_ROUTE = '/governance/guardrails/protections';
const GUARDRAILS_TEST_ROUTE = '/governance/guardrails/test';
const ROUTER_ROUTE = '/runtime/models/routing';

export const RUNTIME_GOVERNANCE_OPERATIONS_AUDITS = [
  audit({
    serviceId: 'console',
    serviceLabel: 'Console',
    upstreamVersion: '61b86a720f725bbd6fdd40d0368e499e22c1bc2e',
    versionSource: `${FLEET_EVIDENCE} release stamp`,
    denominatorSource:
      'src/app/(console) route tree; src/lib/tenancy-policy.ts; src/lib/adapters contracts',
    auditStateEvidence:
      'The fleet verified this immutable release, but the current working release has moved beyond it and is not deployed.',
    summary:
      'Bounded first-party denominator: authenticated operator access, management routes, tenant isolation, and durable run dispatch. Self-restart remains host-owned.',
    capabilities: [
      [
        'authenticated-control-plane',
        'Authenticated tenant control plane',
        'Open the governed management Console with tenant-scoped data and actions.',
        '/operations',
        'Open operations',
        '',
        [
          'yes',
          'The immutable Console release provides session and service-account authorization.',
          'yes',
          'NextAuth, tenancy, authorization, and repository seams are wired.',
          'yes',
          'All canonical domains are reachable through URL-driven Console routes.',
          'yes',
          'The authenticated integration harness exercised bank and insurance tenant routes.',
        ],
      ],
      [
        'tenant-management',
        'Tenant-isolated management state',
        'Create and manage product entities without crossing organization boundaries.',
        '/governance/access',
        'Manage access',
        '',
        [
          'yes',
          'The first-party release includes tenant-owned repositories and authorization rules.',
          'yes',
          'Database, claims, and policy adapters enforce organization scope.',
          'yes',
          'Domain management routes expose tenant-scoped entities and actions.',
          'yes',
          'Bank and insurance seed checks proved isolation of solution records.',
        ],
      ],
      [
        'self-lifecycle',
        'Console process lifecycle',
        'Deploy, restart, and roll back the control plane safely.',
        '/operations/admin',
        'Inspect administration',
        'Keep process lifecycle in the private deployment runbook; expose immutable build and rollback evidence without adding an unsafe self-restart action.',
        [
          'yes',
          'The release has native start, stop, deploy, and rollback runbooks.',
          'partial',
          'Deployment scripts own lifecycle; the running process does not control itself.',
          'partial',
          'Administration explains host ownership but does not execute deployment lifecycle.',
          'yes',
          'The fleet ledger records an immutable release and prepared rollback source.',
        ],
      ],
    ],
  }),
  audit({
    serviceId: 'edge-gateway',
    serviceLabel: 'Network Gateway',
    upstreamVersion: 'Caddy v2.11.4; Coraza Caddy v2.5.0; caddy-ratelimit v0.1.0',
    versionSource:
      'onprem-fleet-orchestration deploy/onprem/edge-runtime-contract.json at bcd5b63; live binary SHA b3764397458fc383c803898b56d5144178dbd9e4742502f3361dff03cd128b5f; live config SHA a5a4b4c29eb214a13cd77d4d5cda00ad0cac4c00b256f9937944cb998b31dd0a',
    denominatorSource:
      'https://github.com/caddyserver/caddy/tree/v2.11.4; https://github.com/corazawaf/coraza-caddy/tree/v2.5.0; https://github.com/mholt/caddy-ratelimit/tree/v0.1.0',
    auditState: 'current',
    summary:
      'Bounded network-edge denominator: host/path proxying, WAF, per-client rate limiting, guarded file delivery, access evidence, and supervised recovery. Cloudflare owns public TLS termination.',
    capabilities: [
      [
        'http-routing',
        'Host and path routing',
        'Route public hosts and bounded API paths to their canonical on-prem owners.',
        '/operations/edge',
        'Inspect edge routes',
        'Route creation and mutation stay deployment-owned; the Console exposes live evidence, not an unsafe ad-hoc proxy editor.',
        [
          'yes', 'Caddy v2.11.4 provides host/path matching, reverse proxy, rewrite, and static responses.',
          'yes', 'The versioned Caddyfile owns the active gateway, AI, webhook, Console, and auxiliary routes.',
          'partial', 'The Edge overview exposes configured traffic and posture but does not mutate the deployment file.',
          'yes', 'Live root, API, file, and webhook routes reached their intended handlers.',
        ],
      ],
      [
        'waf',
        'Web application firewall',
        'Reject scanner, injection, traversal, and script payloads before application code.',
        '/operations/edge/waf',
        'Manage WAF intent',
        'The Console persists desired WAF intent but cannot yet validate and apply/reload it through the host-owned recovery contract.',
        [
          'yes', 'Coraza Caddy v2.5.0 and Coraza v3.7.0 are compiled into the pinned binary.',
          'yes', 'The versioned edge snippet executes Coraza before terminal route handlers.',
          'partial', 'WAF status and intent CRUD exist; applying that intent remains deployment-owned.',
          'yes', 'A live sqlmap user-agent request was rejected with HTTP 403.',
        ],
      ],
      [
        'rate-limiting',
        'Per-client rate limiting',
        'Bound abusive clients with route-specific sliding-window limits.',
        '/operations/edge/traffic',
        'Inspect traffic',
        'Rate policy is visible in traffic evidence but has no safe Console edit/apply workflow.',
        [
          'yes', 'caddy-ratelimit v0.1.0 provides keyed sliding-window limits and Retry-After responses.',
          'yes', 'Rate limiting is ordered after Coraza and before every terminal handle.',
          'partial', 'Operators can inspect traffic but cannot edit or publish rate zones.',
          'yes', 'The live verifier isolated a synthetic client key and observed HTTP 429 after the configured threshold.',
        ],
      ],
      [
        'guarded-file-delivery',
        'Policy-owned file delivery',
        'Serve stable file URLs without bypassing object visibility, tenant, or owner policy.',
        '/work/files',
        'Manage files',
        '',
        [
          'yes', 'Caddy supports path handling, rewrite, and reverse proxy composition.',
          'yes', 'Only /files/media/* is rewritten to the canonical Console file API; arbitrary buckets return 404.',
          'yes', 'The Files surface owns upload, visibility, access, and deletion.',
          'yes', 'Live proof returned 404 for an anonymous private object, 200 with service auth, and 200 for a public seed, then deleted the probe.',
        ],
      ],
      [
        'access-evidence',
        'Access and rejection evidence',
        'Inspect edge traffic and blocked requests from the active JSON access stream.',
        '/operations/edge/blocked-requests',
        'Inspect blocked requests',
        '',
        [
          'yes', 'Caddy v2.11.4 emits structured JSON access logs with rotation.',
          'yes', 'The deploy excludes the runtime log, preserving its inode while Caddy is running.',
          'yes', 'Traffic and Blocked requests consume the canonical edge log adapter.',
          'yes', 'The live verifier observed the current log path grow across allowed and rejected probes.',
        ],
      ],
      [
        'supervised-recovery',
        'Validated edge recovery',
        'Validate exact config and modules before restarting the supervised edge.',
        '/operations/health/metrics',
        'Inspect platform health',
        'Restart remains root-owned by design; expose immutable evidence rather than a browser-triggered privileged action.',
        [
          'yes', 'Caddy provides config validation and supervised lifecycle commands.',
          'yes', 'The fleet recovery contract checks version, binary/config hashes, modules, launchd, policy paths, and log growth.',
          'partial', 'Platform health reports readiness but does not perform privileged host lifecycle actions.',
          'yes', 'Candidate validation, launchd kickstart, and all fail-closed live checks passed on S1.',
        ],
      ],
    ],
  }),
  audit({
    serviceId: 'gateway',
    serviceLabel: 'AI Gateway',
    upstreamVersion: 'Console release 61b86a720f725bbd6fdd40d0368e499e22c1bc2e',
    versionSource:
      'Historical Console release 61b86a720f725bbd6fdd40d0368e499e22c1bc2e; scripts/gateway-aggregator.mjs source owner 55064461a42a76a332392e19ea724a06732203b1; onprem fleet SERVER_STATE.md at bc74d828e02db7566b32191650cb58360f9178ae',
    denominatorSource:
      'packages/gateway/src/index.ts; packages/gateway/src/cluster/types.ts; packages/gateway/src/queue/types.ts; Console cloud-egress contract at c0d3e793: src/lib/egress-dlp.ts, src/lib/egress-dlp-run.ts, src/lib/egress-policy-store.ts, and src/app/api/v1/chat/stream/route.ts',
    auditStateEvidence:
      'Historical auth and routing proof exists, but deploy/push.sh explicitly does not restart the aggregator and the live process has no repo-owned launch artifact or deployed-source stamp. Record the running script checksum, launch manifest revision, PID start time, and expected Console SHA in recover.sh before treating its identity as current.',
    summary:
      'Bounded first-party denominator: authenticated inference, model discovery, fleet routing, and request governance. Direct backend access is not part of the operator contract.',
    capabilities: [
      [
        'authenticated-inference',
        'Authenticated inference',
        'Run OpenAI-compatible inference through the governed on-prem door.',
        '/runtime/gateways',
        'Inspect gateways',
        '',
        [
          'yes',
          'The first-party gateway supports authenticated OpenAI-compatible inference.',
          'yes',
          'src/lib/gateway.ts and the inference adapter call the real gateway with service credentials.',
          'yes',
          'Runtime gateway and model surfaces expose the governed endpoint.',
          'yes',
          'The fleet gate proved a real completion and invalid-bearer rejection.',
        ],
      ],
      [
        'fleet-routing',
        'Fleet model routing',
        'Discover healthy models and route requests across active fleet nodes.',
        '/runtime/models',
        'Manage models',
        '',
        [
          'yes',
          'The gateway aggregator release provides pool membership, health, and routing.',
          'yes',
          'Gateway control and model-catalog adapters consume the real pool.',
          'yes',
          'Models, gateways, nodes, and clusters expose the routing relationship.',
          'yes',
          'The eight-node registry and Qwen/Gemma/Qwythos completions were verified.',
        ],
      ],
      [
        'request-governance',
        'Request policy and guardrail spine',
        'Apply tenancy, policy, guardrails, routing, and audit to inference requests.',
        '/governance/posture',
        'Inspect governance posture',
        'The deployed aggregator proves authentication, attribution, and routing, while policy and guardrails run in the surrounding Console spine. Correlate one allowed and one denied inference across tenant, policy, guard, gateway traffic, and audit evidence before counting the gateway contract as complete.',
        [
          'yes',
          'The first-party gateway release supports the Off Grid governance contract.',
          'partial',
          'Credential, routing, attribution, and traffic paths are in the aggregator; policy and guardrails are enforced by the surrounding Console spine rather than a deployed gateway policy plug-in.',
          'yes',
          'Governance and runtime surfaces expose effective controls and evidence.',
          'partial',
          'Governed denial and merged guard scans passed separately, but the retained evidence does not correlate both with the same gateway request and traffic record.',
        ],
      ],
      [
        'cloud-egress-dlp',
        'Cloud egress DLP',
        'Mask or block sensitive text at the final governed boundary before a chat request is sent to a cloud model.',
        '/governance/egress',
        'Manage cloud egress protection',
        'The final enforcement hook currently covers only the chat/stream cloud-model path immediately before forwardToCloud; agent and app model calls, cloud tools, and outbound sinks do not enter it. Extend the same tenant-scoped, fail-closed boundary to every cloud-egress path before promoting integration to yes.',
        [
          'yes',
          'First-party Console release c5e8e01e1852da63a7094ca99745fb0830af7710 provides a default-on mask policy, strict block mode, fail-closed guardrail handling, and an explicit admin opt-out for cloud-bound text.',
          'partial',
          'The chat stream loads the tenant policy, scans every outbound text unit through the selected PII adapter, replaces payload.messages before forwardToCloud, refuses the call when screening fails, and records gateway.egress.dlp against the current orgId. Coverage remains limited to this chat cloud-model seam.',
          'yes',
          'The URL-driven /governance/egress surface and admin GET/PATCH route expose per-org ON/OFF, mask-versus-block policy, detector readiness, and recent decisions; disabling protection is an explicit audited admin action.',
          'yes',
          'Fleet-verified 2026-07-22 on S1 at c5e8e01e1852da63a7094ca99745fb0830af7710: two temporary org_bharat chat turns containing synthetic PAN ABCDE1234F and an email routed to compat:openai/gpt-4o-mini; the provider-produced answer contained PAN [REDACTED] and [REDACTED_EMAIL_ADDRESS_3], while the tenant panel retained two gateway.egress.dlp masked/redacted decisions. Evidence: docs/screenshots/capabilities/egress-dlp-cloud-response-c5e8e01e.png and egress-dlp-ledger-c5e8e01e-wide.png.',
        ],
      ],
    ],
  }),
  audit({
    serviceId: 'llm-guard',
    serviceLabel: 'Content guardrails',
    upstreamVersion:
      'LLM Guard / llm-guard-api 0.3.16 (tag 32b14a4a2fa398df8b77fd748ee4bd387a4ac5ce; upstream archived and unmaintained)',
    versionSource:
      'off-grid-ai/onprem-fleet-orchestration@bc74d828e02db7566b32191650cb58360f9178ae deploy/onprem/services-node-b.yml (mutable laiyer/llm-guard-api:0.3.16 image tag; live digest not retained), SERVICE_MAP.md, and SERVER_STATE.md; upstream v0.3.16 tag 32b14a4a2fa398df8b77fd748ee4bd387a4ac5ce',
    denominatorSource:
      'https://github.com/protectai/llm-guard/tree/32b14a4a2fa398df8b77fd748ee4bd387a4ac5ce/llm_guard_api; https://github.com/protectai/llm-guard/blob/32b14a4a2fa398df8b77fd748ee4bd387a4ac5ce/llm_guard/input_scanners/__init__.py; https://github.com/protectai/llm-guard/blob/32b14a4a2fa398df8b77fd748ee4bd387a4ac5ce/llm_guard/output_scanners/__init__.py; current upstream README archive warning',
    auditState: 'current',
    summary:
      'Relevant 0.3.16 denominator: prompt analysis/redaction, prompt classifiers, output safety/quality scanners, scanner policy, authenticated and bounded API execution, availability controls, and telemetry. Off Grid sharding is a separate first-party integration. The upstream project and its models are archived and no longer maintained, so this deployment needs a migration owner and compensating security controls.',
    capabilities: [
      [
        'prompt-sanitization',
        'Prompt sanitization and sensitive-data protection',
        'Detect and redact PII, secrets, credentials, and configured text patterns before a model sees them.',
        GUARDRAILS_TEST_ROUTE,
        'Test prompt protection',
        '',
        [
          'yes',
          'LLM Guard 0.3.16 exposes /analyze/prompt and input Anonymize, Regex, and Secrets scanners; the S1 shard has live email/secret redaction evidence.',
          'yes',
          'The content-guardrail port calls the authenticated S1 aggregator, normalizes the real verdict and sanitized prompt, and blocks when the required PII shard cannot answer.',
          'yes',
          'Guardrails Overview, Protections, Masking, Recognizers, Thresholds, and Test expose prompt protection and a live scan action.',
          'yes',
          'Fleet-proven live: governed agent run run_b542fcf7 (org_bharat) redacted the raw PAN/email BEFORE the model (pre-guard pii:redacted + guardrail-rules masked "My PAN is ABCDE1234F"→"****"), then the model answered only from the redacted input — the pre-model redaction + downstream inference are retained together on the signed run. (This path 500-crashed at persist until the guardrail NUL-sentinel fix — the reason durable redacting runs never completed.)',
        ],
      ],
      [
        'prompt-threat-scanning',
        'Prompt threat and content classification',
        'Detect injection, toxicity, gibberish, language, banned content, code, and request-size risks.',
        GUARDRAILS_PROTECTIONS_ROUTE,
        'Manage prompt protections',
        'The deployed g6 shard runs only PromptInjection, Toxicity, Gibberish, and Language from the 15-class 0.3.16 input denominator. Its optional-shard degradation header is discarded by the Console adapter, and catalog entries for other scanners do not reconfigure the static shard.',
        [
          'yes',
          'The pinned input-scanner module exports 15 scanner classes, including injection, toxicity, content restrictions, language, code, regex, secrets, and token limits.',
          'partial',
          'The Off Grid aggregator fans out to a required PII shard and an optional g6 classifier shard; g6 statically enables four input classifiers and merged verdicts are normalized.',
          'partial',
          'Protections exposes ten scanner cards and pipeline/org scope, but several cards are not present in deployed YAML and an enable action does not change the upstream scanner set.',
          'partial',
          'Fleet recovery proved a merged injection/toxicity-classifier plus PII response, but not a seeded bank or insurance journey and not optional-shard degradation visibility.',
        ],
      ],
      [
        'output-safety-quality',
        'Output safety and quality scanning',
        'Evaluate and sanitize model output for bias, sensitive content, relevance, factual consistency, refusal, malicious URLs, language, format, and toxicity.',
        GUARDRAILS_PROTECTIONS_ROUTE,
        'Inspect output protections',
        'Output scanning is wired to /analyze/output and retained per run; extend the deployed output-scanner set (add e.g. MaliciousURLs/Bias) and capture a retained run where the output guard BLOCKS, to move the workflow gate to full.',
        [
          'yes',
          'LLM Guard 0.3.16 exposes /scan/output and /analyze/output and exports 22 output scanner classes/variants spanning safety, policy, and quality.',
          'yes',
          'The content-guardrail adapter scanOutput() posts to /analyze/output with the prompt context; checks.ts post-phase routes through it (NOT the input endpoint). Live-verified: a toxic answer returned is_valid:false with Toxicity tripped (Sensitive/Regex -1); the normalizer maps that real shape to a blocked/redacted verdict (contract test pinned).',
          'partial',
          'The catalog names PII, toxicity, bias, and banned-topic output outcomes, but it does not manage or display actual output scanner configuration and results.',
          'partial',
          'Governed runs retain a post-phase output-guard verdict (e.g. run_f7aa3cb5 has a retained post /analyze/output pii check); the deployed output-scanner set is limited (Sensitive/Regex/Toxicity) and a retained run where the output guard BLOCKS is not yet captured.',
        ],
      ],
      [
        'scanner-policy-lifecycle',
        'Scanner configuration and lifecycle',
        'Select scanners, tune thresholds and parameters, suppress scanners per request, and roll out policy safely.',
        GUARDRAILS_PROTECTIONS_ROUTE,
        'Manage protection policy',
        'Make deployed YAML or its replacement policy store the single lifecycle owner. In 0.3.16 scanner definitions are static configuration and requests only support scanners_suppress; the Console currently sends an unsupported scanners object, so catalog scope and custom India recognizers do not alter the stock service.',
        [
          'yes',
          'The 0.3.16 API loads ordered input/output scanners and parameters from CONFIG_FILE, supports lazy loading and per-request scanners_suppress, and has no scanner CRUD API.',
          'partial',
          'The fleet owns versioned classifier YAML and first-party shard merge policy, but the S1 PII configuration is not represented here and request-body scanner configuration is ignored upstream.',
          'partial',
          'Console rules, recognizers, thresholds, and pipeline scope are CRUD-capable product state, but they are not reconciled into the selected upstream 0.3.16 static configuration.',
          'no',
          'No retained workflow proves that changing a Console scanner rule changes the scanners or parameters executed by either shard.',
        ],
      ],
      [
        'api-auth-rate-limits',
        'Authenticated and bounded scan API',
        'Protect scan endpoints with bearer/basic authentication and configurable request limits.',
        '/governance/secrets',
        'Manage service credentials',
        'Expose guard service credential rotation and effective rate-limit posture without leaking secrets; retain valid/invalid credential and throttling evidence.',
        [
          'yes',
          'The 0.3.16 API supports HTTP bearer or basic auth and configurable per-client rate limiting.',
          'yes',
          'The Console and aggregator send bearer credentials from protected deployment configuration; shard tokens remain node-local.',
          'no',
          'The Console has no LLM-Guard-specific credential rotation or effective rate-limit management surface.',
          'partial',
          'Authenticated live scan evidence exists, but invalid-token, rotation, and throttling behavior are not retained as one governed workflow.',
        ],
      ],
      [
        'availability-failure-policy',
        'Availability, timeouts, and failure policy',
        'Probe liveness/readiness, bound scanner latency, and choose fail-fast or aggregate behavior.',
        GUARDRAILS_ROUTE,
        'Inspect guardrail posture',
        'Expose required versus optional shard readiness and degradation. Today /healthz only proves the aggregator process, /readyz is not consumed, and an optional classifier outage is hidden from the normalized Console verdict.',
        [
          'yes',
          'LLM Guard 0.3.16 provides /healthz and /readyz, prompt/output timeouts, scan_fail_fast, lazy loading, and deterministic HTTP errors.',
          'partial',
          'The Console bounds requests and fails closed on adapter/required-shard failure; Off Grid adds required/optional shard policy, but optional degradation is not propagated to the port result.',
          'partial',
          'Overview shows configured/reachable state, but not readiness, per-shard health, model load state, degradation, latency, or recovery actions.',
          'partial',
          'Fleet recovery proves merged service behavior and required-shard recovery mechanics; it does not retain a governed-run outage/recovery journey.',
        ],
      ],
      [
        'telemetry',
        'Scanner telemetry',
        'Observe scanner verdict counts, latency, errors, traces, and service saturation.',
        '/insights/ai/overview',
        'Inspect AI behavior',
        'Configure and attribute the 0.3.16 Prometheus/OTel signals, retain per-scanner and per-shard evidence, and connect them to actionable Console diagnostics. Console logs alone are not this upstream telemetry path.',
        [
          'yes',
          'LLM Guard 0.3.16 supports Prometheus or OTLP metrics, OTLP/console tracing, structured logs, and per-scanner validity counters.',
          'no',
          'No production adapter reads or attributes LLM Guard metrics/traces; the deployed classifier config defaults traces to console and has no retained telemetry pipeline proof.',
          'no',
          'AI behavior and platform health do not expose LLM Guard scanner metrics, shard saturation, or trace evidence.',
          'no',
          'No bank or insurance journey links a guardrail verdict to upstream scanner telemetry.',
        ],
      ],
    ],
  }),
  audit({
    serviceId: 'keycloak',
    serviceLabel: 'Identity & SSO',
    upstreamVersion: '26.0.7',
    versionSource:
      'deploy/docker-compose.yml (quay.io/keycloak/keycloak:26.0.7); live docker ps on S1 verified 2026-07-23 — container offgrid-console-keycloak-1 running the pinned 26.0.7 image',
    denominatorSource: 'https://www.keycloak.org/docs/26.0.7/server_admin/',
    auditState: 'current',
    summary:
      'Relevant denominator: human SSO, service accounts, tenant access, session/revocation controls, and identity lifecycle. Full realm administration is intentionally abstracted.',
    capabilities: [
      [
        'human-sso',
        'Human SSO and sessions',
        'Authenticate operators through the configured enterprise identity provider.',
        '/governance/access',
        'Manage access',
        'Prove the production Keycloak provider, logout, revocation, and session-expiry lifecycle; authenticated access alone is not the full lifecycle.',
        [
          'yes',
          'Keycloak 26.0.7 provides OIDC realms, clients, and user sessions.',
          'partial',
          'NextAuth has Keycloak support, but production-provider lifecycle evidence is incomplete.',
          'yes',
          'Access and team surfaces manage product membership and roles.',
          'partial',
          'Authenticated tenant sessions passed; logout/revocation/expiry were not re-verified.',
        ],
      ],
      [
        'service-accounts',
        'Service-account grants',
        'Issue client-credential grants to internal service adapters without hard-coded bearer tokens.',
        '/governance/access',
        'Inspect service access',
        'Expose the bounded client lifecycle and revocation posture without recreating raw realm administration.',
        [
          'yes',
          'Keycloak supports confidential clients and client-credential grants.',
          'yes',
          'The service credential broker exchanges OpenBao-held client secrets for grants.',
          'partial',
          'Access surfaces show product access; full client lifecycle is not a dedicated UI.',
          'yes',
          'Five client-credential grants passed in the fleet recovery evidence.',
        ],
      ],
      [
        'federation-mfa',
        'Federation and MFA policy',
        'Federate workforce identity and require suitable authentication assurance.',
        '/governance/access',
        'Manage access',
        'Audit the configured identity-provider and authentication-flow contracts, then expose assurance and recovery state without recreating raw Keycloak administration.',
        [
          'yes',
          'Keycloak 26.0.7 supports identity brokering and configurable authentication flows.',
          'no',
          'No production federation/MFA adapter contract is evidenced.',
          'no',
          'The Console does not expose federation or MFA posture.',
          'no',
          'No seeded bank or insurance identity-assurance workflow is verified.',
        ],
      ],
    ],
  }),
  audit({
    serviceId: 'temporal',
    serviceLabel: 'Durable Workflows',
    upstreamVersion: 'Temporal Server 1.25.2 / UI 2.32.0',
    versionSource:
      'onprem-fleet-orchestration deploy/onprem/services-node-a.yml (tags temporalio/auto-setup:1.25.2, temporalio/ui:2.32.0). Live image digests locked 2026-07-20 in SERVER_STATE.md: auto-setup@sha256:b1edc1e20002d958c8182f2ae08dee877a125083683a627a44917683419ba6a8, ui@sha256:82bf98dbe005a831b6bc5dc12ccd7bffd606af2032dae4821ae133caaa943d3d.',
    denominatorSource: 'https://docs.temporal.io/',
    auditState: 'current',
    summary:
      'Relevant denominator: durable app/agent/chat dispatch, run lifecycle, schedules, retries, visibility, cancellation, and worker readiness.',
    capabilities: [
      [
        'durable-dispatch',
        'Durable app, agent, and chat dispatch',
        'Submit governed work to durable task queues and preserve run history.',
        '/operations/runs',
        'Inspect runs',
        '',
        [
          'yes',
          'Temporal 1.25.2 provides durable workflows, activities, histories, and task queues.',
          'yes',
          'App, agent, chat, schedule, and visibility adapters use Temporal clients and workers.',
          'yes',
          'Operations runs and app/agent run detail pages expose durable state.',
          'yes',
          'The fleet C4 gate retained a 202 response with workflowId for an eligible governed run, then correlated its completed output and actor evidence; the Temporal Server/UI image digests are now locked in SERVER_STATE.md (2026-07-20).',
        ],
      ],
      [
        'run-actions',
        'Run cancellation, retry, and replay',
        'Intervene in a failed or long-running workflow without losing audit history.',
        '/operations/runs',
        'Manage runs',
        '',
        [
          'yes',
          'Temporal supports termination, cancellation, reset/replay, and retry semantics.',
          'yes',
          'The comprehensive adapter covers the full matrix on durable app-run workflows: cancelWorkflow (cancel/terminate) + row reconciliation, resetWorkflow (reset/replay from the first workflow task), and rerun via submitAppRun; eligibility is the pure decideAppRunControl.',
          'yes',
          'The app Runs tab renders status-appropriate controls on every run via availableAppRunControls: cancel/terminate for in-flight runs, replay/re-run for terminal runs.',
          'yes',
          'Verified live on the fleet 2026-07-20 through POST /api/v1/admin/app-runs/{id}/workflow: terminate killed running workflows and reconciled the row to cancelled; reset replayed a done run (apprun_f339b0ee: done→running, re-executing from its first task); rerun dispatched a fresh run (apprun_f339b0ee→apprun_96e8d21d, 201); the pure guard returned 400 on a bad action and 409 on ineligible state (cancel-a-done, reset-in-flight).',
        ],
      ],
      [
        'worker-readiness',
        'Worker and task-queue readiness',
        'Know whether app, agent, and chat queues have compatible pollers before accepting work.',
        '/operations/services/temporal',
        'Inspect workers',
        '',
        [
          'yes',
          'Temporal exposes task-queue pollers and worker build/versioning primitives.',
          'yes',
          'adapters/worker-readiness.ts probes DescribeTaskQueue directly (pure shaper task-queue-readiness.ts), reporting per-queue poller identity/count/backlog — readiness is no longer inferred from run state.',
          'yes',
          'The temporal/app-worker/agent-worker/chat-worker detail pages render a live readiness panel (WorkerReadinessPanel) with per-queue poller identity, count, and backlog.',
          'yes',
          'Verified live on the fleet 2026-07-20: /api/v1/admin/workers/readiness returned offgrid-apps, offgrid-agents, and offgrid-chat each with a compatible poller (e.g. 44550@offgrid-s1); the console rendered "3/3 queues ready".',
        ],
      ],
    ],
  }),
  audit({
    serviceId: 'app-worker',
    serviceLabel: 'App Worker',
    upstreamVersion:
      'First-party source 21bd2f1ab450a531c031df6167dd3aee2a800971 / @temporalio/worker 1.20.2',
    versionSource:
      'Console git snapshot 21bd2f1ab450a531c031df6167dd3aee2a800971; package-lock.json; onprem-fleet-orchestration launch manifest 3e91d5d357e824dabfe6a97a3bc0015b897c37c6',
    denominatorSource:
      'scripts/app-worker.mts; src/lib/app-run-durable.ts; src/lib/adapters/apprun.ts; src/worker/app-run.workflow.ts; src/worker/app-run.activities.ts; src/lib/app-run.ts; src/lib/app-run-resume.ts; src/lib/app-run-store.ts',
    auditState: 'current',
    summary:
      'Pinned first-party denominator: worker artifact identity, queue readiness, governed step execution, durable human review, failure recovery, and output persistence. Code-path evidence is kept separate from live worker proof.',
    capabilities: [
      [
        'artifact-identity',
        'Immutable worker artifact identity',
        'Identify the exact app-worker source, runtime dependency, launch contract, and deployed artifact before assigning work.',
        '/operations/services/app-worker',
        'Inspect app worker',
        '',
        [
          'yes',
          'The first-party worker source, Temporal Worker SDK 1.20.2, and launch-manifest revision are pinned independently.',
          'yes',
          'Each worker registers with Temporal identity <pid>@<host>#<sha8> — the deployed release SHA (from the immutable deploy/.deployed-sha stamp or OFFGRID_RELEASE_SHA) resolved by the pure worker-artifact-identity module — binding the running poller to its exact deployed artifact.',
          'yes',
          'The app-worker service-detail readiness panel surfaces the artifact SHA badge parsed from each live poller identity.',
          'yes',
          'Verified live on the fleet 2026-07-20: after deploy of SHA 2b256bbc, DescribeTaskQueue reported the offgrid-apps/offgrid-agents/offgrid-chat pollers as <pid>@offgrid-s1#2b256bbc — the live pollers correlated to the exact deployed artifact stamped in deploy/.deployed-sha.',
        ],
      ],
      [
        'task-queue-readiness',
        'Task queue and poller readiness',
        'Confirm a compatible app worker is polling offgrid-apps before durable work is accepted.',
        '/operations/services/app-worker',
        'Inspect app worker',
        '',
        [
          'yes',
          'scripts/app-worker.mts creates a Temporal Worker on the configured queue and fails startup when required runtime configuration is invalid.',
          'yes',
          'adapters/worker-readiness.ts probes DescribeTaskQueue for offgrid-apps and reports the app-worker poller identity/count/backlog directly — not inferred from Temporal availability or an eventual run state.',
          'yes',
          'The app-worker service detail page renders the live offgrid-apps poller (identity, count, backlog) via WorkerReadinessPanel.',
          'yes',
          'Verified live on the fleet 2026-07-20: after a worker restart, offgrid-apps reported compatible poller 44550@offgrid-s1 through the deployed /api/v1/admin/workers/readiness endpoint and rendered "Ready" in the console.',
        ],
      ],
      [
        'governed-step-execution',
        'Governed step execution',
        'Execute app steps with tenant, actor, pipeline, policy, guardrail, routing, and provenance context intact.',
        '/solutions/apps',
        'Manage apps',
        '',
        [
          'yes',
          'The pinned worker implements read-data, connector, agent, guardrail, human, and output step contracts.',
          'yes',
          'executeStepActivity re-resolves the app and pipeline binding at execution time and reuses the production governed step executor with organization and actor context.',
          'yes',
          'App build, run, review, report, and operations-run routes expose the complete operator journey.',
          'yes',
          'Verified live on the fleet 2026-07-20: bhapp_fnol (org_bharat) ran on the app-worker durable path (workflowId apprun-bhapp_fnol-apprun_f339b0ee, resumedInline:false) executing connector, agent (policy+guardrail+PII-mask+grounding), human, and output steps under its bound pipeline; run apprun_f339b0ee completed done with the agent step attributed to child run run_356ec4a8.',
        ],
      ],
      [
        'human-pause-resume',
        'Durable human pause and resume',
        'Pause a multi-step app at an authority gate, preserve history, and resume or reject it through an audited decision.',
        '/solutions/reviews',
        'Open review queue',
        '',
        [
          'yes',
          'The workflow waits durably on a review signal and models approval, rejection, and edited output.',
          'yes',
          'The review API signals Temporal first, preserves paused state when the service is unreachable, and uses the inline resume adapter only when durable execution is not configured or not found.',
          'yes',
          'The review queue and run detail routes expose the pending decision and permitted action.',
          'yes',
          'Verified live on the fleet 2026-07-20 via durable Temporal signals (resumedInline:false): apprun_f339b0ee paused → approved → resumed → completed done; apprun_4440547c paused → rejected → halted to error; a repeat decision on a terminal run returned 409 (canReview guard). The approve-authority (unauthorized/under-threshold approver → 403) is covered by app-access-policy + app-access integration tests.',
        ],
      ],
      [
        'failure-recovery',
        'Failure and restart recovery',
        'Retry transient step failures and survive worker loss without duplicating side effects or losing the operator-visible run.',
        '/operations/runs',
        'Inspect durable runs',
        'Worker-loss recovery is proven live; worker build/version compatibility, an operator-visible safe-drain control, and a verified per-step side-effect idempotency contract are still outstanding.',
        [
          'yes',
          'Temporal histories, bounded activity retries, deterministic workflow IDs, and launchd KeepAlive provide the required recovery primitives.',
          'partial',
          'The workflow has retry policy and deterministic dispatch, but the worker lacks build-version compatibility, safe drain, and a verified side-effect idempotency contract for every step.',
          'partial',
          'Run detail exposes failure state and actions, but app-worker safe-drain and poller build-compatibility are not operator-visible.',
          'yes',
          'Verified live on the fleet 2026-07-21: paused run apprun_fe17e9f5 survived an app-worker kill+restart (remained awaiting_human across the worker-loss), was then approved via a durable signal (resumedInline:false), and the RESTARTED worker resumed and completed it (done) — an interrupted app-worker run recovered after process restart.',
        ],
      ],
      [
        'output-persistence',
        'Output and run-state persistence',
        'Persist step state, final output, report artifacts, and provenance so an operator can inspect and act on the result later.',
        '/operations/runs',
        'Inspect run outputs',
        'persistState still swallows database errors with no replay/backfill repair path, and recovery of a completed output after a missed write is not yet proven; the completed-output/row/provenance correlation is now live-proven.',
        [
          'yes',
          'The app runtime defines app_runs persistence, aggregate output, signed report artifacts, and Temporal workflow history.',
          'partial',
          'The worker persists state around transitions, but persistState intentionally swallows database errors and has no replay or backfill repair path.',
          'yes',
          'App and operations run detail/report routes expose persisted status, output, and artifacts when writes succeed.',
          'yes',
          'Verified live on the fleet 2026-07-20: run apprun_f339b0ee completed done with all five steps persisted (including the output step) and its agent child run run_356ec4a8 carrying a signed ed25519 provenance — a worker-completed output correlated to its database row and provenance record.',
        ],
      ],
    ],
  }),
  audit({
    serviceId: 'opa',
    serviceLabel: 'Policy Engine',
    upstreamVersion: '0.70.0',
    versionSource:
      'onprem-fleet-orchestration deploy/onprem/services-node-a.yml (configured tag openpolicyagent/opa:0.70.0); live `opa version` in container offgrid-services-a-opa-1 on S1 verified 2026-07-23 → Version 0.70.0, Build Commit 2ea031ea04e6a8afbc5dd22f656131dc3cfc5a7d',
    denominatorSource: 'https://www.openpolicyagent.org/docs/v0.70.0/',
    auditState: 'current',
    summary:
      'Relevant denominator: policy/module/data lifecycle, decision evaluation, bundles, decision logs, and failure posture. Rego stays behind governed product modules.',
    capabilities: [
      [
        'policy-decisions',
        'Governed policy decisions',
        'Evaluate tenant-scoped allow/deny decisions and preserve explainable evidence.',
        '/governance/policies/decisions',
        'Inspect decisions',
        '',
        [
          'yes',
          'OPA 0.70.0 provides policy evaluation and decision APIs.',
          'yes',
          'OFFGRID_ADAPTER_POLICY=opa is the selected adapter on both the console and the agent-worker (retained in the fleet .env.local); decisions are attributed engine:opa. First-party ABAC remains only as an unreachable-OPA safety fallback.',
          'yes',
          'Policies and evidence routes expose rules and decisions.',
          'yes',
          'Live: the offgrid/authz Rego was deployed via the console (HTTP 201, OPA-compiled); operator→allow and viewer→deny via /api/v1/admin/abac/evaluate both returned engine:opa; governed agent run run_9733f803 (Succeeded) recorded its policy step as label opa — "allow — OPA decision (offgrid/authz): true" (docs/screenshots/capabilities/policy-opa-run-attribution.png). Attribution is to OPA, not the ABAC fallback.',
        ],
      ],
      [
        'policy-lifecycle',
        'Policy and module lifecycle',
        'Create, edit, publish, version, and retire governed policy rules.',
        '/governance/policies/rules',
        'Manage rules',
        '',
        [
          'yes',
          'OPA provides policy and data document APIs.',
          'yes',
          'The console policy-module route deploys/compiles/publishes Rego to the live OPA (deployModule → PUT /v1/policies/{id}); invalid Rego is rejected at the gate before it can land.',
          'yes',
          'Rules, templates, modules, and decisions have canonical nested routes.',
          'yes',
          'Live: offgrid/authz was created + compiled + published (HTTP 201) and immediately changed OPA decisions (reload); an invalid Rego was rejected (HTTP 400 rego_parse_error "2:24 unexpected : token") and never landed in OPA (404 in storage); redeploy is idempotent (rollback = republish the prior module).',
        ],
      ],
      [
        'bundles-decision-logs',
        'Bundles and decision-log export',
        'Distribute policy safely and export complete decision telemetry.',
        '/governance/policies/decision-logs',
        'Inspect decision logs',
        'End-to-end OPA-pushed decision logs need the OPA decision_logs plugin pointed at the console ingest endpoint (a deploy-config step, not a console change); live bundles need OPA started with a bundle config. Both are surfaced honestly today.',
        [
          'yes',
          'OPA 0.70.0 supports bundles and decision-log plugins.',
          'yes',
          'A governed decision-log SINK (opa-audit adapter + self-migrating opa_decision_logs store) reads OPA /v1/config,/status,/policies and ingests + persists OPA decision-log uploads; bundle status is read from OPA. Verified live against OPA 0.70.0 on the box.',
          'yes',
          'Governance → Policies → Decision logs is a list→detail ledger (filters, aggregate, purge) + an honest read-only bundles view.',
          'partial',
          'Fleet-proven live: a decision event ingested → persisted → listed + aggregated (deny, engine:opa); the deployed OPA has decision_logs + bundles UNconfigured, so a real OPA-pushed log needs that deploy-config flip.',
        ],
      ],
    ],
  }),
  audit({
    serviceId: 'openbao',
    serviceLabel: 'Secrets Vault',
    upstreamVersion: '2.1.0',
    versionSource:
      'deploy/docker-compose.yml (openbao/openbao:2.1.0); live GET /v1/sys/health on S1:8200 verified 2026-07-23 → version 2.1.0, sealed:false',
    denominatorSource: 'https://openbao.org/docs/2.1.x/',
    auditState: 'current',
    summary:
      'Relevant denominator: secret CRUD, connector and service credentials, leases, mounts, rotation, auth, policy, audit, and recovery. Root administration is excluded.',
    capabilities: [
      [
        'secret-lifecycle',
        'Tenant secret lifecycle',
        'Create, read, update, and delete governed secrets without revealing values in client state.',
        '/governance/secrets/keys',
        'Manage keys',
        '',
        [
          'yes',
          'OpenBao 2.1.0 provides versioned KV secret lifecycle APIs.',
          'yes',
          'The secrets adapter and connector-secret seam perform server-side lifecycle operations.',
          'yes',
          'Keys and connector forms expose product-owned secret operations.',
          'yes',
          'Full CRUD proven live through the console routes against the unsealed OpenBao 2.1.0 (KV v2): WRITE (201) → LIST (key present, value NEVER in the JSON) → UPDATE → version metadata shows v1+v2 → soft-DELETE (v2 deletionTime set, v1 retained) — all tenant-scoped to org_bharat/ and recorded as secret.write rows in audit_events_v2. Screenshot: docs/screenshots/capabilities/secrets-lifecycle-keys.png.',
        ],
      ],
      [
        'dynamic-credentials',
        'Dynamic database credentials and leases',
        'Issue short-lived credentials, inspect leases, and revoke access.',
        '/governance/secrets/dynamic-database',
        'Manage dynamic credentials',
        '',
        [
          'yes',
          'OpenBao 2.1.0 provides database secrets and lease APIs.',
          'yes',
          'The database secrets engine is enabled at database/ against the console Postgres with a scoped read-only role (demo-readonly, default_ttl 2m/max 10m); the console dynamic-db route mints on-demand creds and the leases route lists them. Replayable via fleet setup-openbao-dynamic-db.sh.',
          'yes',
          'Dynamic database and lease routes are deep-linkable; the Dynamic-database view lists roles with a Generate-creds action (screenshot secrets-dynamic-db-role.png).',
          'yes',
          'Fleet-proven live end-to-end: MINT via the console governed route returned a real short-lived Postgres user (v-root-demo-rea-…, lease database/creds/demo-readonly/…); the cred AUTHENTICATED to Postgres (AUTH_OK, can_read=true); least-privilege held (DDL → "permission denied for schema public"); REVOKE (HTTP 204) then the same cred FATAL-failed to connect (role dropped). Issue→auth→least-privilege→revoke→teardown all observed.',
        ],
      ],
      [
        'vault-recovery',
        'Vault audit and disaster recovery',
        'Back up encrypted state, inspect audit devices, and recover without credential loss.',
        '/operations/backups',
        'Manage backups',
        'Backup → restore → unseal → verify + audit-device drill proven live and recorded (fleet vault-recovery-drill.sh). Next: surface the drill/backup record in the /operations/backups UI.',
        [
          'yes',
          'OpenBao supports file-backed storage, audit devices, and operational recovery procedures.',
          'yes',
          'A replayable drill (fleet vault-recovery-drill.sh) backs up the encrypted file-storage volume and restores it into a fresh vault; a file audit device is enabled and records requests with HMAC-obscured values.',
          'partial',
          'The /operations/backups surface lists backups but does not yet render this OpenBao restore drill as a first-class record.',
          'yes',
          'Fleet-proven live (non-destructive): a canary was written to the live vault; the encrypted data volume was tarred (29K, keyring included) and restored into a throwaway vault on :8201 (initialized:true/sealed:true); the SAME Shamir key unsealed it (sealed:false — no credential loss); the canary read back MATCHED (encryption keyring intact); a file audit device logged the read with the secret value HMAC-hashed, not plaintext. Throwaway + canary cleaned up.',
        ],
      ],
    ],
  }),
  audit({
    serviceId: 'unleash',
    serviceLabel: 'Feature Flags',
    upstreamVersion: '6.6 mutable minor tag',
    versionSource: 'deploy/docker-compose.yml (unleashorg/unleash-server:6.6)',
    denominatorSource: 'https://docs.getunleash.io/reference',
    auditStateEvidence:
      'The configured 6.6 tag is not digest-pinned; the live immutable upstream version is unknown.',
    summary:
      'Relevant denominator: flag CRUD, enablement, rollout strategies, variants, environment state, and audited product use. The mutable tag prevents a current availability claim.',
    capabilities: [
      [
        'flag-lifecycle',
        'Feature-flag lifecycle',
        'Create, describe, enable, disable, and archive product flags.',
        '/operations/configuration',
        'Manage configuration',
        'Pin the live image and prove create-to-archive through the operator UI.',
        [
          'yes',
          'Unleash 6.6 documentation describes feature CRUD and environment enablement.',
          'yes',
          'Admin adapters implement create, description update, toggle, and archive.',
          'partial',
          'Configuration consumes flags; complete lifecycle discoverability is not live-proven.',
          'no',
          'No seeded end-to-end flag lifecycle is recorded.',
        ],
      ],
      [
        'progressive-rollout',
        'Progressive rollout and variants',
        'Roll out a capability gradually and choose controlled variants.',
        '/operations/configuration',
        'Manage rollouts',
        'Prove a tenant-scoped percentage rollout and variant changes real product behavior.',
        [
          'yes',
          'Unleash 6.6 provides strategies and variants.',
          'yes',
          'Adapters implement rollout percentages and variant payloads.',
          'partial',
          'No dedicated rollout/variant journey is evidenced in the Console.',
          'no',
          'No bank or insurance workflow is verified under a rollout.',
        ],
      ],
    ],
  }),
  audit({
    serviceId: 'redis',
    serviceLabel: 'Redis',
    upstreamVersion: '7.4.9 (redis:7.4-alpine)',
    versionSource:
      'deploy/docker-compose.yml (redis:7.4-alpine); live `redis-cli INFO server` in container offgrid-services-b-redis-1 on g6 verified 2026-07-23 → redis_version:7.4.9',
    denominatorSource: 'https://redis.io/docs/latest/develop/',
    auditState: 'current',
    summary:
      'Relevant denominator: shared response-cache get/set/expiry/invalidation, backend health, and graceful fallback. Redis remains an implementation behind the cache port.',
    capabilities: [
      [
        'shared-response-cache',
        'Shared response cache',
        'Cache governed responses across Console processes with bounded expiry.',
        '/operations/services/redis',
        'Inspect Redis',
        'Prove the deployed runtime selects Redis and expose hit, miss, expiry, and invalidation evidence.',
        [
          'yes',
          'Redis 7.4 provides key/value storage and expiry.',
          'partial',
          'The cache port supports Redis, but the running backend is not identified in evidence.',
          'partial',
          'Service detail exposes health, not cache operations or metrics.',
          'no',
          'No production request trace proves a Redis hit or invalidation.',
        ],
      ],
      [
        'failure-fallback',
        'Cache failure fallback',
        'Continue safely on an in-process cache when Redis is unavailable.',
        '/operations/health',
        'Inspect health',
        'Prove failover and recovery under a real connection loss without hiding stale data.',
        [
          'yes',
          'The Off Grid cache contract defines an in-process fallback.',
          'yes',
          'The Redis adapter degrades to the in-process implementation.',
          'partial',
          'Health labels the fallback; operators cannot inspect transition history.',
          'no',
          'No deployed failover/recovery workflow is recorded.',
        ],
      ],
    ],
  }),
  audit({
    serviceId: 'superset',
    serviceLabel: 'BI & Dashboards',
    upstreamVersion: '4.1.1',
    versionSource:
      'deploy/docker-compose.yml (apache/superset:4.1.1); live docker ps on g6 verified 2026-07-23 — container offgrid-services-b-superset-1 running the pinned 4.1.1 image',
    denominatorSource: 'https://superset.apache.org/docs/6.0.0/intro',
    auditState: 'current',
    summary:
      'Relevant operator denominator: governed dashboard provisioning, native chart read-back, embedded access, and bounded authoring. Superset remains the query engine; the Console owns the operator experience.',
    capabilities: [
      [
        'dashboard-provisioning',
        'Governed dashboard provisioning',
        'Idempotently create the Off Grid database, dataset, charts, and dashboard.',
        '/insights/usage/dashboards',
        'Manage dashboards',
        '',
        [
          'yes',
          'Superset 4.1.1 provides database, dataset, chart, dashboard, and embedded-config APIs.',
          'yes',
          'src/lib/superset.ts authenticates and performs idempotent find-or-create provisioning.',
          'yes',
          'Insights > Usage > Dashboards is the canonical governed dashboard route.',
          'yes',
          'The fleet ledger records dashboard 1 and charts 1 and 2 provisioned through the Console API.',
        ],
      ],
      [
        'native-chart-readback',
        'Native governed chart read-back',
        'Run Superset chart queries and render the results inside the Off Grid visual system.',
        '/insights/usage/dashboards',
        'View dashboards',
        '',
        [
          'yes',
          'Superset 4.1.1 provides chart-data APIs.',
          'yes',
          'src/lib/superset-data.ts resolves owned charts, runs chart-data queries, and shapes results.',
          'yes',
          'The Console renders the governed dashboard in its native Insights surface.',
          'yes',
          'The provisioned request and token charts query the live Console database.',
        ],
      ],
      [
        'embedded-access',
        'Scoped embedded dashboard access',
        'Mint short-lived guest access only after verifying the owned dashboard exists.',
        '/insights/usage/dashboards',
        'Open governed dashboard',
        'Capture one immutable guest-token and expiry/revocation workflow; configured code alone is not production proof.',
        [
          'yes',
          'Superset 4.1.1 supports embedded dashboard configuration and guest tokens.',
          'yes',
          'The Superset adapter verifies the dashboard before minting a scoped guest token.',
          'yes',
          'The dashboard route can open the governed embedded resource.',
          'partial',
          'Dashboard provisioning is proven, but guest-token expiry and revocation are not in fleet evidence.',
        ],
      ],
      [
        'sql-authoring',
        'Advanced SQL and chart authoring',
        'Let authorized analysts explore governed data and publish additional visualizations.',
        '/insights/usage/dashboards',
        'Open dashboard tools',
        'Define the analyst authorization boundary and either integrate bounded authoring or explicitly keep it in the separately authenticated Superset surface.',
        [
          'yes',
          'Superset 4.1.1 provides SQL Lab, datasets, charts, and dashboards.',
          'partial',
          'The Console provisions its owned assets but does not wrap the full authoring lifecycle.',
          'partial',
          'Operators can link to Superset; authoring is not a native Off Grid CRUD surface.',
          'no',
          'No seeded analyst authoring workflow is verified.',
        ],
      ],
    ],
  }),
  audit({
    serviceId: 'fleetdm',
    serviceLabel: 'Device Management',
    upstreamVersion: '4.87.0',
    versionSource:
      'deploy/docker-compose.yml (fleetdm/fleet:v4.87.0); live docker ps on g6 verified 2026-07-23 — container offgrid-services-b-fleet-1 running the pinned v4.87.0 image',
    denominatorSource: 'https://fleetdm.com/docs/rest-api/rest-api',
    auditState: 'current',
    summary:
      'Relevant Community-edition denominator: host inventory, live/saved queries, software/CVE visibility, and policies. Premium MDM control is explicitly unsupported without licensing.',
    capabilities: [
      [
        'host-inventory-software',
        'Host and software inventory',
        'Inspect enrolled devices, installed software, and vulnerability context.',
        '/operations/devices',
        'Manage devices',
        'Complete operator setup, enroll a real test host, and prove inventory refresh.',
        [
          'yes',
          'Fleet 4.87.0 Community provides host and software inventory.',
          'yes',
          'Fleet adapters map hosts and software inventory.',
          'yes',
          'Operations device list and detail routes expose inventory.',
          'no',
          'The live fleet has no operator-owned enrollment evidence.',
        ],
      ],
      [
        'queries-policies',
        'Live queries and compliance policies',
        'Run bounded osquery queries and manage host compliance checks.',
        '/operations/devices',
        'Manage device posture',
        'Prove one safe query and one policy lifecycle against an enrolled live host.',
        [
          'yes',
          'Fleet 4.87.0 Community provides queries, campaigns, and policies.',
          'yes',
          'Adapters and routes implement live query and policy CRUD.',
          'yes',
          'Device surfaces expose query and policy actions.',
          'no',
          'No enrolled-host query or policy evidence is recorded.',
        ],
      ],
      [
        'premium-mdm',
        'Premium device control',
        'Lock, wipe, and push configuration profiles to managed devices.',
        '/operations/devices',
        'Inspect device controls',
        'Keep these controls unavailable until a compatible Fleet Premium license, server capability, enrollment, and live safety proof exist.',
        [
          'no',
          'The deployed Community configuration does not establish Premium MDM availability.',
          'partial',
          'Adapters model commands but gate unavailable controls.',
          'partial',
          'The UI can explain unavailability without presenting a working control.',
          'no',
          'No device-control workflow is verified.',
        ],
      ],
    ],
  }),
  {
    serviceId: 'presidio',
    serviceLabel: 'Presidio',
    upstreamVersion: '2.2.356',
    versionSource: 'deploy/docker-compose.yml',
    denominatorSource: 'https://microsoft.github.io/presidio/api-docs/',
    auditedAt: '2026-07-19',
    auditState: 'current',
    auditStateEvidence: null,
    summary:
      'Text analysis, replacement anonymization, org recognizers, deny lists, and thresholds are integrated into the data-redaction path. Language and advanced anonymizer operations remain narrow.',
    items: [
      defineCapability(
        'text-analysis',
        'Text entity analysis',
        'Detect built-in PII entities and return typed spans with confidence scores.',
        '/governance/guardrails/test',
        'Test live detection',
        '',
        [
          'yes',
          'The analyzer image exposes /analyze.',
          'yes',
          'scanWithPresidio posts a typed analyze request and applies returned spans.',
          'yes',
          'The Guardrails test surface runs the active engine.',
          'yes',
          'The selected data-redaction adapter runs in app and data-movement policy checks.',
        ],
      ),
      defineCapability(
        'replace-anonymization',
        'Replacement anonymization',
        'Send analyzed spans to the anonymizer and replace values with entity markers.',
        '/governance/guardrails/test',
        'Test live redaction',
        '',
        [
          'yes',
          'The anonymizer image exposes /anonymize with replace operators.',
          'yes',
          'The adapter calls analyzer then anonymizer and has a span-safe local fallback.',
          'yes',
          'The test surface displays the redacted result and active engine.',
          'yes',
          'Data-redaction workflows consume the returned redacted text.',
        ],
      ),
      defineCapability(
        'pattern-recognizers',
        'Custom pattern recognizers',
        'Create org-scoped regex and context recognizers and send them per analyze request.',
        '/governance/guardrails/recognizers',
        'Manage recognizers',
        '',
        [
          'yes',
          'Presidio accepts ad_hoc_recognizers with regex patterns and context.',
          'yes',
          'Stored recognizers are normalized and merged into every analyze request.',
          'yes',
          'The recognizers route provides create, update, enable, and delete controls.',
          'yes',
          'The same org policy is loaded by the real data-redaction adapter.',
        ],
      ),
      defineCapability(
        'deny-lists',
        'Custom deny lists',
        'Flag fixed org-specific terms as a named PII entity.',
        '/governance/guardrails/recognizers',
        'Manage deny lists',
        '',
        [
          'yes',
          'PatternRecognizer supports deny_list values.',
          'yes',
          'Deny lists are translated into enabled ad hoc recognizers.',
          'yes',
          'The recognizer manager supports deny-list CRUD.',
          'yes',
          'Enabled deny lists are loaded into production analyze requests.',
        ],
      ),
      defineCapability(
        'confidence-thresholds',
        'Global and per-entity thresholds',
        'Set an org floor and stricter or looser thresholds by entity type.',
        '/governance/guardrails/thresholds',
        'Manage thresholds',
        '',
        [
          'yes',
          'The analyzer accepts a request score threshold.',
          'yes',
          'The global floor is sent upstream and per-entity thresholds are enforced on returned scores.',
          'yes',
          'The thresholds route edits the org policy.',
          'yes',
          'The real adapter loads and applies the org threshold policy.',
        ],
      ),
      defineCapability(
        'languages',
        'Language selection and multilingual analysis',
        'Choose a supported language and recognizer set for each analysis request.',
        PRESIDIO_ROUTE,
        'Inspect Presidio status',
        'The adapter has a language parameter but every production call defaults to en. Add supported-language discovery, validation, and an org or pipeline setting before advertising multilingual detection.',
        [
          'yes',
          'Presidio supports language-specific recognizers.',
          'partial',
          'The request builder accepts language, but the registered port never supplies a non-English value.',
          'no',
          'There is no language control on the Guardrails surface.',
          'no',
          'Production scans are fixed to English.',
        ],
      ),
      defineCapability(
        'advanced-anonymizers',
        'Mask, hash, encrypt, redact, and custom operators',
        'Apply an anonymizer operator per entity instead of fixed replacement markers.',
        '/governance/guardrails/masking',
        'Open masking policy',
        'The adapter hard-codes replace. Add a validated operator policy, secret-backed encryption keys, reversible-data handling, and UI controls before exposing advanced operators.',
        [
          'yes',
          'Presidio anonymizer ships multiple operator types.',
          'partial',
          'The analyzer-to-anonymizer flow is wired, but only replace is constructed.',
          'no',
          'Masking rules do not configure Presidio anonymizer operators.',
          'no',
          'No production workflow selects a non-replace operator.',
        ],
      ),
      defineCapability(
        'image-redaction',
        'Image PII redaction',
        'Detect and redact PII in images and scanned documents.',
        PRESIDIO_ROUTE,
        'Inspect Presidio status',
        'The deployed analyzer/anonymizer pair has no image-redactor adapter, API route, or review UI.',
        [
          'yes',
          'Presidio provides an image redactor capability.',
          'no',
          'No image-redactor service or adapter is registered.',
          'no',
          'No image redaction UI exists.',
          'no',
          'No document or media workflow invokes Presidio image redaction.',
        ],
      ),
    ],
  },
  {
    serviceId: 'litellm',
    serviceLabel: 'LiteLLM',
    upstreamVersion: 'main-stable (mutable image tag)',
    versionSource: 'deploy/docker-compose.yml',
    denominatorSource: 'https://docs.litellm.ai/docs/',
    auditedAt: '2026-07-19',
    auditState: 'current',
    auditStateEvidence: null,
    summary:
      'The router config generator, management read-back, and inference endpoint seam are built. The live model-door cutover and callback delivery remain unverified, so routing and enforcement do not count as production use.',
    items: [
      defineCapability(
        'openai-proxy',
        'OpenAI-compatible inference proxy',
        'Serve chat and model requests through a single OpenAI-compatible model door.',
        ROUTER_ROUTE,
        'Inspect inference wiring',
        'The endpoint resolver can select LiteLLM, but the audited deployment has no verified live cutover. Run chat and governed pipeline traffic through the selected provider and record the serving deployment.',
        [
          'yes',
          'LiteLLM Proxy exposes OpenAI-compatible inference APIs.',
          'yes',
          'The gateway endpoint seam resolves LiteLLM URL and bearer credentials.',
          'yes',
          'The Routing view shows the selected inference door.',
          'partial',
          'Production request paths support the seam, but live LiteLLM cutover is not verified.',
        ],
      ),
      defineCapability(
        'load-balance-failover',
        'Load balancing, retries, and failover',
        'Route a model alias across fleet and cloud deployments with health-aware retry policy.',
        ROUTER_ROUTE,
        'Inspect routing health',
        'Generated config enables routing policy, but no live multi-node failure drill proves failover on the production model door.',
        [
          'yes',
          'LiteLLM Router supports deployment groups, health-aware balancing, retries, and fallbacks.',
          'yes',
          'The generated config defines model groups, retry policy, and deployment metadata.',
          'yes',
          'The Routing view displays deployment health.',
          'no',
          'No verified production cutover or failure drill exists.',
        ],
      ),
      defineCapability(
        'deployment-inventory',
        'Deployment inventory and health',
        'Read configured models and merge them with healthy and unhealthy endpoint state.',
        ROUTER_ROUTE,
        'Inspect deployments',
        '',
        [
          'yes',
          'LiteLLM exposes model info and health endpoints.',
          'yes',
          'safeRouterView merges /model/info and /health without fabricating missing deployments.',
          'yes',
          'The Routing view renders deployment, model, egress, vision, and health.',
          'yes',
          'Operations can inspect the configured LiteLLM service independently of model-door selection.',
        ],
      ),
      defineCapability(
        'budgets-rate-limits',
        'Budgets and RPM/TPM limits',
        'Enforce spend and request limits on virtual keys.',
        ROUTER_ROUTE,
        'Inspect key budget',
        'Full key + budget/RPM/TPM CRUD is live over LiteLLM DB-backed FinOps, and REQUEST-RATE enforcement (RPM) is fleet-verified. IMPORTANT honesty caveat: LiteLLM dollar-budgets are cost-based, so they only bite when the routed model carries a per-token price — on the on-prem/free models the demo runs, every call computes $0 spend, so a dollar max_budget never trips (verified: two calls on a $1e-7-budget key both returned 200 and key spend stayed 0.0). For free local models RPM/TPM are the effective control; dollar-budgets bind cloud/cost-bearing routes. Next: register model cost for cost-bearing routes + surface per-key spend trends + audit records on key mutations.',
        [
          'yes',
          'LiteLLM supports per-key budget, RPM, and TPM controls.',
          'yes',
          'The adapter creates/updates/deletes/lists keys with max_budget + rpm/tpm via LiteLLM /key/generate|update|delete|list (litellm-key-policy builds the bodies + shapes rows).',
          'yes',
          'The Routing view Virtual-keys panel manages budgets + RPM/TPM (create, edit-budget, revoke) with live spend/utilization + over-budget badges.',
          'partial',
          'REQUEST-RATE enforcement is fleet-proven live: a key with rpm_limit=2 admitted requests 1-2 (HTTP 200) and BLOCKED requests 3-6 (HTTP 429 "Rate limit exceeded ... Current limit: 2, Remaining: 0"). But the SPEND half of this capability does NOT enforce on the demo routes: dollar-budget enforcement was NOT observed on free on-prem models — a $1e-7-budget key served calls with spend stuck at 0.0 (no model cost → no spend → budget never trips). So the workflow is partial: RPM/TPM bind, dollar-budgets are a $0 no-op until cost-bearing/cloud routes carry a per-token price.',
        ],
      ),
      defineCapability(
        'virtual-keys',
        'Virtual key lifecycle',
        'Create, rotate, revoke, scope, and inspect LiteLLM virtual keys.',
        ROUTER_ROUTE,
        'Inspect current key snapshot',
        '',
        [
          'yes',
          'LiteLLM exposes virtual key management APIs.',
          'yes',
          'The adapter runs the full lifecycle — generateVirtualKey / listVirtualKeys / updateVirtualKey / deleteVirtualKeys — over LiteLLM /key/*.',
          'yes',
          'The Virtual-keys panel creates (alias + budget + RPM/TPM), edits, and revokes keys; the new token is shown once, list rows show only the masked token.',
          'yes',
          'Fleet-proven live: keys created + listed + revoked through the console admin routes against LiteLLM DB-backed /key/* (litellm-database image; requires the DB enabled, now codified in deploy-g5-model-router.sh).',
        ],
      ),
      defineCapability(
        'provider-pools',
        'Fleet and cloud provider pools',
        'Generate deployment entries for on-prem nodes and approved cloud providers.',
        '/runtime/models/providers',
        'Inspect model providers',
        'The generator consumes fleet and environment inputs, but the console does not own a validated LiteLLM config publish or reload transaction.',
        [
          'yes',
          'LiteLLM supports many providers behind model aliases.',
          'yes',
          'buildLiteLLMConfig maps fleet nodes and cloud providers to model_list entries.',
          'partial',
          'Provider status is visible, but it is not a LiteLLM pool editor.',
          'no',
          'No production workflow publishes and reloads generated config through the console.',
        ],
      ),
      defineCapability(
        'structured-callbacks',
        'Structured request logging callbacks',
        'Send completion outcomes, deployment, tokens, caller, latency, and status into traffic records.',
        '/runtime/models/callbacks',
        'Open callback stream',
        'Runtime add/remove of a callback sink is config-owned on the deployed LiteLLM version (set at deploy + reload); the console reads and surfaces the active sinks honestly and manages them where the version allows.',
        [
          'yes',
          'LiteLLM emits StandardLoggingPayload callbacks and exposes its configured success/failure callback sinks.',
          'yes',
          'The litellm-callbacks adapter reads the live proxy callback config + health and normalizes the StandardLoggingPayload shape (litellm-log-shape). Verified live: reachable+active, real sinks (_ProxyDBLogger, deployment_callback_on_success).',
          'yes',
          'AI Runtime → Models → Callbacks shows active sinks, health, and a per-call payload preview.',
          'partial',
          'Fleet-proven live: the deployed LiteLLM reports its active callback sinks through the console; enabling a NEW sink (e.g. Langfuse/OTel) is a proxy-config + reload step on this version.',
        ],
      ),
      defineCapability(
        'spend-analytics',
        'Spend and cost analytics',
        'Attribute request cost by key, model, deployment, team, and time window.',
        '/runtime/models/spend',
        'Open gateway spend',
        'The LiteLLM-native attribution surface at /runtime/models/spend is wired — the spend adapter reads LiteLLM /spend/logs and rolls up by model, virtual-key, and time bucket with a per-request drill-down — but is not yet fleet-verified end-to-end through those new routes. The console-native cost-by-model/user/project/time path (Insights → Cost) remains fleet-proven, so the aggregate workflow gate is partial until the LiteLLM-ledger surface is exercised live.',
        [
          'yes',
          'LiteLLM (DB-backed proxy) tracks per-request spend and exposes it over /spend/logs (+ optional /global/spend/keys|models rollups); the console additionally meters the audit/traffic log with per-model pricing (finops.priceFor/costForTokens).',
          'yes',
          'Two adapters cover it: assembleFinOps buckets real per-request token counts × price into cost by model/user/project, and adapters/litellm-spend.ts reads LiteLLM /spend/logs and rolls up by model/virtual-key/time-bucket in the pure litellm-spend.ts (window parsing, normalization, aggregation, summary — unit-tested).',
          'yes',
          'Insights → Cost (Models/Users/Projects/Overview) attributes spend with pipeline + time-window filters, and the new gateway FinOps surface at /runtime/models/spend attributes spend/tokens/requests by model, by virtual-key, and over time (24h/7d/30d) with a per-request drill-down — honestly leading with tokens/volume and labelling $0 on free on-prem models.',
          'partial',
          'Fleet-proven live for the console-native path: cost-by-model shows real usage (Qwen 2.5 14B — 53 requests, 74,808 tokens; GPT-4o-mini — 4 requests) priced into spend, filterable by pipeline + window; local models correctly report $0. The LiteLLM-ledger per-virtual-key surface is code+wired but its live read through /api/v1/admin/gateway/spend is not yet fleet-verified.',
        ],
      ),
      defineCapability(
        'response-cache',
        'Response caching',
        'Cache eligible model responses with explicit privacy, scope, and expiry policy.',
        '/runtime/models/cache',
        'Open response cache',
        'Response caching is NOT enabled in the deployed LiteLLM proxy (/cache/ping → 503 "litellm.cache is None"), so no cache hit/flush workflow can be exercised. Enabling it is a proxy-config + reload concern outside the console; the surface reads status/stats + offers flush the moment caching is turned on.',
        [
          'yes',
          'LiteLLM supports response cache backends.',
          'yes',
          'The litellm-cache adapter calls /cache/ping (status/type/policy), /cache/flushall|/cache/delete (flush), and derives hit-rate/tokens-saved from /spend/logs cache_hit markers — verified live reaching the real proxy and surfacing its 503 "cache not initialized" honestly.',
          'yes',
          'AI Runtime → Models → Cache shows cache effectiveness (hit-rate/tokens/cost, honest "not reported" when no marker), live cache status, and flush actions — verified rendering the real disabled state.',
          'no',
          'Deployed ≠ used: the proxy has caching disabled (litellm.cache is None), so no real cache hit or flush has been exercised; hit-rate + flush become live once caching is enabled in the proxy config.',
        ],
      ),
      defineCapability(
        'proxy-guardrails',
        'Proxy guardrails and policy hooks',
        'Run supported guardrails in the proxy before or after model calls.',
        ROUTER_ROUTE,
        'Inspect router capabilities',
        'Governance remains in the Off Grid pipeline spine. That is a valid ownership choice, but LiteLLM guardrail capability is not integrated and must not be counted.',
        [
          'yes',
          'LiteLLM supports proxy guardrail integrations.',
          'no',
          'No LiteLLM guardrail is configured or adapted.',
          'no',
          'The Router view has no proxy guardrail controls.',
          'no',
          'Production governance runs in the Off Grid policy and guardrail spine instead.',
        ],
      ),
    ],
  },
] as const satisfies readonly ServiceCapabilityAudit[];

/**
 * These services belong to this lane but still lack a versioned upstream denominator. Keeping the
 * IDs explicit proves inventory coverage while leaving the canonical capability summary honestly
 * `not-audited`.
 */
export const RUNTIME_GOVERNANCE_OPERATIONS_UNAUDITED_SERVICE_IDS = [
  'gateway-control',
  'agent-worker',
  'chat-worker',
  'cloudflared',
  'landing',
  'status-page',
  'litellm-forwarder',
  'observability-forwarder',
  'fleet-forwarder',
] as const;

export const RUNTIME_GOVERNANCE_OPERATIONS_SERVICE_IDS = [
  ...RUNTIME_GOVERNANCE_OPERATIONS_AUDITS.map((record) => record.serviceId),
  ...RUNTIME_GOVERNANCE_OPERATIONS_UNAUDITED_SERVICE_IDS,
] as const;
