'use client';

import { ArrowsOut, X } from '@phosphor-icons/react/dist/ssr';
import { useTheme } from 'next-themes';
import { useEffect, useState } from 'react';

// ─── The control-plane poster ─────────────────────────────────────────────────────────────────────
//
// The whole product as one technical drawing: edge intelligence, the governed console, and the
// business outcomes. It is a TRUE VECTOR SVG generated by `tools/oga-universe/build.py`, so the type
// stays crisp at any size and any device pixel ratio, and it is themeable in place.
//
// TWO REAL ASSETS, NOT A CSS INVERSION. The poster depicts the console, and the console is itself
// light/dark — so the palette is resolved at build time and each theme is its own file. Inverting the
// light SVG with a CSS filter would wreck the embedded device screenshots and turn the emerald into
// magenta. `--theme dark` in the generator uses the console's own dark tokens (background #0a0a0a,
// surface #141414, emerald #34d399), so the poster and the product it shows agree.
//
// ONLY ONE FILE IS FETCHED. Rendering both and hiding one with `dark:hidden` would download ~260 KB
// of poster the visitor never sees. The `src` follows the resolved theme instead, and until the theme
// is known nothing is requested — which also avoids fetching the light asset and then immediately
// replacing it on a landing page that defaults to dark.
//
// THE FINE PRINT IS TEXTURE, AND THERE IS A WAY TO READ IT. At hero size the headline, the section
// titles and the structure are legible while the 6px labels read as detail — the impression of a real
// system. Nobody can read those in a column, so the poster opens full size. A dense diagram with no
// way to read it is decoration.

const SRC = {
  light: '/hero/control-plane-light.svg',
  dark: '/hero/control-plane-dark.svg',
} as const;

const ALT =
  'The Off Grid AI enterprise AI control plane: on-device intelligence at the edge, a governed console with gateways, pipelines and data connectors, and the business outcomes it produces';

export function ControlPlanePoster() {
  const { resolvedTheme } = useTheme();
  const [mounted, setMounted] = useState(false);
  const [open, setOpen] = useState(false);

  // `resolvedTheme` is undefined until next-themes has read the stored preference. Waiting avoids
  // requesting the wrong asset first and swapping it a moment later.
  useEffect(() => setMounted(true), []);
  const src = resolvedTheme === 'light' ? SRC.light : SRC.dark;

  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') setOpen(false);
    };
    window.addEventListener('keydown', onKey);
    // The full-size view owns the viewport; let it, rather than scrolling the page behind it.
    const previous = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    return () => {
      window.removeEventListener('keydown', onKey);
      document.body.style.overflow = previous;
    };
  }, [open]);

  return (
    <>
      <button
        type="button"
        onClick={() => setOpen(true)}
        aria-label="Open the control plane diagram full size"
        className="group relative block w-full overflow-hidden rounded-xl border border-border bg-card shadow-[0_24px_70px_-30px_rgba(5,150,105,0.35)] transition-shadow hover:shadow-[0_28px_80px_-28px_rgba(5,150,105,0.5)]"
      >
        {/* Reserve the aspect ratio so the hero does not reflow when the poster lands. */}
        <span className="block" style={{ aspectRatio: '1535 / 1024' }}>
          {mounted ? (
            // eslint-disable-next-line @next/next/no-img-element -- an SVG must not go through the
            // raster optimizer: next/image would rasterize it and throw away the reason it is vector.
            <img src={src} alt={ALT} width={1535} height={1024} className="h-full w-full" />
          ) : null}
        </span>
        <span className="pointer-events-none absolute bottom-3 right-3 inline-flex items-center gap-1.5 rounded-md border border-border bg-background/95 px-2 py-1 font-mono text-[10px] uppercase tracking-[0.14em] text-muted-foreground opacity-0 shadow-sm transition-opacity group-hover:opacity-100 group-focus-visible:opacity-100">
          <ArrowsOut className="size-3 text-primary" weight="bold" />
          View full size
        </span>
      </button>

      {open ? (
        <div
          role="dialog"
          aria-modal="true"
          aria-label="The Off Grid AI enterprise AI control plane, full size"
          className="fixed inset-0 z-50 flex flex-col bg-background/97 backdrop-blur-sm"
        >
          <div className="flex shrink-0 items-center justify-between gap-3 border-b border-border px-4 py-3">
            <p className="flex items-center gap-2 font-mono text-[11px] uppercase tracking-[0.2em] text-muted-foreground">
              <span className="size-1.5 rounded-full bg-primary" />
              <span className="text-foreground">Enterprise AI control plane</span>
            </p>
            <button
              type="button"
              onClick={() => setOpen(false)}
              autoFocus
              className="inline-flex items-center gap-1.5 rounded-md border border-border bg-card px-2.5 py-1.5 font-mono text-[11px] uppercase tracking-[0.14em] text-muted-foreground hover:text-foreground"
            >
              <X className="size-3.5" />
              Close
            </button>
          </div>
          {/* Deliberately larger than most viewports and scrollable both ways — at full size the
              reader pans a real diagram instead of squinting at a shrunk one. */}
          <div className="min-h-0 flex-1 overflow-auto p-4" onClick={() => setOpen(false)}>
            {/* eslint-disable-next-line @next/next/no-img-element -- see above */}
            <img
              src={src}
              alt={ALT}
              width={1535}
              height={1024}
              onClick={(e) => e.stopPropagation()}
              className="mx-auto h-auto w-full min-w-[1100px] max-w-[1535px] rounded-lg border border-border"
            />
          </div>
        </div>
      ) : null}
    </>
  );
}
