// ─── Cross-Sell Cockpit weekly digest — PURE, zero-IO ─────────────────────────────────────────────
//
// Renders the cockpit metrics into an email report (subject + plain text + HTML), reused by BOTH the
// scheduled weekly send and the on-demand "Send report now" action. Pure — no imports beyond the
// metric types + INR formatter, unit-testable in test/cockpit-digest.test.ts. Aggregate insights
// only; no individual PII (names/PANs never enter the digest body).

import type { CockpitMetrics } from './cockpit-metrics';
import { formatInr, formatPct } from './cockpit-metrics';

export interface CockpitDigest {
  subject: string;
  text: string;
  html: string;
}

export function buildCockpitDigest(
  metrics: CockpitMetrics,
  opts?: { appTitle?: string; note?: string },
): CockpitDigest {
  const title = opts?.appTitle ?? 'Cross-Sell Advisor';
  const { kpi, funnel, productMix, topOpportunities } = metrics;

  const subject = `${title} — weekly cockpit · ${formatInr(kpi.pipelineValueInr)} open pipeline`;

  const kpiLines = [
    ['Assets under management', formatInr(kpi.totalAumInr)],
    ['Customers in book', String(kpi.customerCount)],
    ['Open pipeline', formatInr(kpi.pipelineValueInr)],
    ['Expected (weighted)', formatInr(kpi.expectedPipelineInr)],
    ['Conversion rate', formatPct(kpi.conversionRate)],
  ] as const;

  const funnelLine = funnel.map((f) => `${cap(f.stage)} ${f.count}`).join('  ·  ');
  const topProduct = productMix[0] ? `${productMix[0].product} (${productMix[0].holders})` : '—';

  const text = [
    `${title} — weekly cockpit`,
    opts?.note ? `\nNote: ${opts.note}` : '',
    '',
    'HEADLINE',
    ...kpiLines.map(([k, v]) => `  ${k}: ${v}`),
    '',
    `FUNNEL   ${funnelLine}`,
    `TOP PRODUCT   ${topProduct}`,
    '',
    'TOP CROSS-SELL OPPORTUNITIES (call these first)',
    ...topOpportunities.map(
      (o, i) => `  ${i + 1}. ${o.nextBestProduct} · ${o.segment}/${o.region} · ${cap(o.stage)} · ${formatInr(o.expectedValueInr)}`,
    ),
    '',
    'Generated by Off Grid AI — governed on-prem, aggregate insights only, individual PII masked.',
  ]
    .filter((l) => l !== '')
    .join('\n');

  const html = `
<div style="font-family:ui-monospace,Menlo,monospace;max-width:640px;color:#0f1115">
  <h2 style="margin:0 0 4px">${esc(title)} — weekly cockpit</h2>
  ${opts?.note ? `<p style="color:#4b5563;margin:0 0 12px">${esc(opts.note)}</p>` : ''}
  <table style="width:100%;border-collapse:collapse;margin:12px 0">
    ${kpiLines
      .map(
        ([k, v]) =>
          `<tr><td style="padding:6px 0;color:#4b5563">${esc(k)}</td><td style="padding:6px 0;text-align:right;font-weight:600">${esc(v)}</td></tr>`,
      )
      .join('')}
  </table>
  <p style="margin:8px 0"><strong>Funnel</strong> — ${esc(funnelLine)}</p>
  <h3 style="margin:16px 0 4px">Top cross-sell opportunities</h3>
  <ol style="margin:0;padding-left:18px">
    ${topOpportunities
      .map(
        (o) =>
          `<li style="margin:3px 0">${esc(o.nextBestProduct)} · ${esc(o.segment)}/${esc(o.region)} · ${esc(cap(o.stage))} · <strong>${esc(formatInr(o.expectedValueInr))}</strong></li>`,
      )
      .join('')}
  </ol>
  <p style="color:#059669;font-size:12px;margin-top:16px">✓ Governed on-prem · aggregate insights only · individual PII masked</p>
</div>`.trim();

  return { subject, text, html };
}

function cap(s: string): string {
  return s.length ? s[0].toUpperCase() + s.slice(1) : s;
}

function esc(s: string): string {
  return s.replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c] ?? c);
}
