import { chromium } from 'playwright';
const BASE='http://127.0.0.1:3005';
const b=await chromium.launch(); const ctx=await b.newContext();
const csrf=(await (await ctx.request.get(`${BASE}/api/auth/csrf`)).json()).csrfToken;
await ctx.request.post(`${BASE}/api/auth/callback/dev`,{form:{csrfToken:csrf,email:'dev@offgrid.local',password:'dev',callbackUrl:`${BASE}/`},maxRedirects:0}).catch(()=>{});
const runs=(await (await ctx.request.get(`${BASE}/api/v1/admin/app-runs?limit=200`)).json()).data||[];
const waiting=runs.filter(r=>r.status==='awaiting_human');
const apps=(await (await ctx.request.get(`${BASE}/api/v1/admin/apps?limit=200`)).json());
const appIds=new Set((apps.data||apps.apps||[]).map(a=>a.id));
console.log('waiting runs:',waiting.length,'appIds known:',appIds.size);
for(const r of waiting) console.log(' ',r.id,'| app=',r.appId, appIds.has(r.appId)?'(app EXISTS)':'(app MISSING from list)','| started',r.startedAt);
await b.close();
