-- Close the schema drift between src/db/schema.ts and drizzle/*.sql so a FRESH database built from
-- the migrations alone matches the schema the app compiles against.
--
-- WHY this file exists: several tables/columns were only ever created at cold start by the stores'
-- self-migrating `ensure*Schema()` DDL (app-versions-store, evidently-projects-store, app-run-store,
-- agentrun, apps-store, data-domains-store) and never landed in a migration. That worked in dev and
-- on the fleet — every write path calls its ensure() first — but it made the migrations an incomplete
-- record: a database built from `drizzle/*.sql` was missing 3 tables and 18 columns, so the
-- *.integration.test.ts suites that read those tables through Drizzle directly (no ensure() on the
-- read path) failed with `column "data_classification" does not exist`. That is what kept Postgres
-- out of CI: the suites hard-failed instead of running. Live finding (2026-08-04): the diff is
-- entirely ADDITIVE — 3 CREATE TABLE, 18 ADD COLUMN, indexes, zero DROP / ALTER TYPE.
--
-- Generated by `drizzle-kit generate` from the 0010 snapshot, then TRIMMED of the statements that the
-- hand-written 0011_sop_template_reuse.sql (apps template columns) and
-- 0012_action_outcome_observations.sql (the observation table) already own — both are now registered
-- in meta/_journal.json and are therefore applied by `drizzle-kit migrate` BEFORE this file.
--
-- Every statement is idempotent (IF NOT EXISTS), matching the house style of 0011/0012, because the
-- fleet database has already self-migrated most of this via ensure*Schema(): this file must be safe to
-- hand-apply there (drizzle-kit push hangs over SSH — paste into psql instead). Column defs MUST
-- match src/db/schema.ts AND the ensure*Schema() DDL exactly.

CREATE TABLE IF NOT EXISTS "app_versions" (
	"id" text PRIMARY KEY NOT NULL,
	"app_id" text NOT NULL,
	"org_id" text DEFAULT 'default' NOT NULL,
	"version" integer NOT NULL,
	"snapshot" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"note" text DEFAULT '' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" text DEFAULT '' NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "drift_projects" (
	"id" text PRIMARY KEY NOT NULL,
	"org_id" text DEFAULT 'default' NOT NULL,
	"name" text NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"dataset" text DEFAULT '' NOT NULL,
	"drift_threshold" double precision DEFAULT 0.25 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "agent_runs" ADD COLUMN IF NOT EXISTS "data_classification" text;--> statement-breakpoint
ALTER TABLE "agent_runs" ADD COLUMN IF NOT EXISTS "policy_version" integer;--> statement-breakpoint
ALTER TABLE "agent_runs" ADD COLUMN IF NOT EXISTS "lawful_basis" text;--> statement-breakpoint
ALTER TABLE "app_runs" ADD COLUMN IF NOT EXISTS "data_classification" text;--> statement-breakpoint
ALTER TABLE "app_runs" ADD COLUMN IF NOT EXISTS "app_version" integer;--> statement-breakpoint
ALTER TABLE "app_runs" ADD COLUMN IF NOT EXISTS "policy_version" integer;--> statement-breakpoint
ALTER TABLE "app_runs" ADD COLUMN IF NOT EXISTS "lawful_basis" text;--> statement-breakpoint
ALTER TABLE "custom_agents" ADD COLUMN IF NOT EXISTS "owner_app_id" text;--> statement-breakpoint
ALTER TABLE "custom_agents" ADD COLUMN IF NOT EXISTS "pipeline_id" text;--> statement-breakpoint
ALTER TABLE "data_domains" ADD COLUMN IF NOT EXISTS "classification" text;--> statement-breakpoint
ALTER TABLE "data_domains" ADD COLUMN IF NOT EXISTS "lawful_basis" text;--> statement-breakpoint
ALTER TABLE "data_domains" ADD COLUMN IF NOT EXISTS "purpose" text;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "app_versions_app_idx" ON "app_versions" USING btree ("app_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "app_versions_org_idx" ON "app_versions" USING btree ("org_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "drift_projects_org_idx" ON "drift_projects" USING btree ("org_id");
