import { type Icon as LucideIcon } from '@phosphor-icons/react';
import {
  ChartBar as BarChart3,
  ChatCircleDots as ChatIcon,
  Robot as Bot,
  BookOpenText,
  Brain,
  Buildings as Building2,
  Coins,
  Cube,
  Database,
  FolderOpen,
  Graph,
  Microscope,
  Devices as MonitorSmartphone,
  ShareNetwork as Network,
  ShieldWarning,
  Scales as Scale,
  Scroll as ScrollText,
  ShieldCheck,
  SquaresFour,
  TextAlignLeft,
  TreeStructure,
  UsersThree,
  UsersFour,
  Vault,
  HardDrive,
  Eye,
  Sliders,
  Code,
  ClockCounterClockwise,
  Gavel,
  Flask,
  Waveform,
  Archive,
  SealCheck,
  Gauge,
  Receipt,
  ClipboardText,
  Toolbox,
  Wrench,
  StackSimple as Stack,
  FlowArrow,
  Broadcast,
  Pulse,
  TrendUp,
} from '@phosphor-icons/react/dist/ssr';
import { type ModuleId } from './registry';

export const MODULE_ICONS: Record<ModuleId, LucideIcon> = {
  overview: Gauge,
  chat: ChatIcon,
  services: SquaresFour,
  projects: FolderOpen,
  artifacts: Cube,
  prompts: TextAlignLeft,
  fleet: MonitorSmartphone,
  gateway: Network,
  gateways: Stack,
  pipelines: FlowArrow,
  edge: ShieldWarning,
  control: ShieldCheck,
  data: Database,
  brain: Brain,
  agents: Bot,
  studio: Graph,
  tools: Wrench,
  observability: Microscope,
  analytics: BarChart3,
  roi: TrendUp,
  finops: Coins,
  accounting: Receipt,
  reports: ScrollText,
  lineage: TreeStructure,
  regulatory: Scale,
  trust: ShieldCheck,
  integrations: Vault,
  'tool-catalog': Toolbox,
  'data-domains': TreeStructure,
  catalog: Database,
  governance: ShieldCheck,
  knowledge: BookOpenText,
  access: UsersThree,
  teams: UsersFour,
  admin: Building2,
  storage: HardDrive,
  provit: Eye,
  'api-docs': Code,
  'agent-runs': ClockCounterClockwise,
  runs: Pulse,
  policy: Gavel,
  evals: Flask,
  siem: ShieldWarning,
  audit: ClipboardText,
  drift: Waveform,
  backups: Archive,
  retrieval: Database,
  provenance: SealCheck,
  secrets: Vault,
  exporters: Broadcast,
  guardrails: ShieldCheck,
  sandbox: Cube,
  config: Sliders,
};
