import { type Icon as LucideIcon } from '@phosphor-icons/react';
import {
  ChartBar as BarChart3,
  ChatCircleDots as ChatIcon,
  Robot as Bot,
  BookOpenText,
  Brain,
  Buildings as Building2,
  Coins,
  Cube,
  Database,
  FolderOpen,
  Graph,
  Microscope,
  Devices as MonitorSmartphone,
  ShareNetwork as Network,
  Scales as Scale,
  Scroll as ScrollText,
  ShieldCheck,
  SquaresFour,
  TextAlignLeft,
  TreeStructure,
  UsersThree,
  Vault,
} from '@phosphor-icons/react/dist/ssr';
import { type ModuleId } from './registry';

export const MODULE_ICONS: Record<ModuleId, LucideIcon> = {
  chat: ChatIcon,
  services: SquaresFour,
  projects: FolderOpen,
  artifacts: Cube,
  prompts: TextAlignLeft,
  fleet: MonitorSmartphone,
  gateway: Network,
  control: ShieldCheck,
  data: Database,
  brain: Brain,
  agents: Bot,
  studio: Graph,
  observability: Microscope,
  analytics: BarChart3,
  finops: Coins,
  reports: ScrollText,
  lineage: TreeStructure,
  regulatory: Scale,
  integrations: Vault,
  knowledge: BookOpenText,
  access: UsersThree,
  admin: Building2,
};
