import { NextResponse } from 'next/server';
import { requireUser } from '@/lib/authz';
import { buildProofPoints, type ProofInput } from '@/lib/guide-proof';
import { DEFAULT_CURRENCY, formatMoney } from '@/lib/money';
import { currentOrgId } from '@/lib/tenancy';

export const dynamic = 'force-dynamic';

// ── GET /api/v1/admin/guide/proof ─────────────────────────────────────────────────────────────────
//
// The live figures behind the guide's "Prove it" list. Every number is COMPUTED from the same readers
// that back the pages — never generated by a model — because the claim being settled is "this is real
// software", and a figure a model wrote cannot settle it.
//
// Every source is read independently and allowed to fail on its own. One unconfigured service must not
// blank the other four claims, and a failed read becomes `null` (rendered as "not available") rather
// than 0: a zero is a claim, and "nothing was blocked" is a very different statement from "we could
// not ask".
//
// Read-only and org-scoped like every other tenant read, so a demo viewer sees only their own tenant's
// evidence.

/** Run one reader, returning null on any failure so a single dead source cannot blank the list. */
async function safe<T>(read: () => Promise<T>): Promise<T | null> {
  try {
    return await read();
  } catch {
    return null;
  }
}

export async function GET(req: Request) {
  const gate = await requireUser(req);
  if (gate instanceof NextResponse) return gate;
  const orgId = await currentOrgId();

  // EVERY reader here takes `orgId` as a REQUIRED leading argument. That is not incidental: this is a
  // tenant surface, and two of the console's cross-tenant leaks came from readers whose org parameter
  // was optional. A reader without an org predicate (the process-global policy decision log, for one)
  // is not eligible for this list at any price — a proof point that shows another bank's numbers is
  // worse than no proof point.
  const [runs, work, egress, finops, provenance, audit, roi] = await Promise.all([
    safe(async () => {
      const { listAllRuns } = await import('@/lib/runs-monitor-reader');
      return listAllRuns(orgId);
    }),
    safe(async () => {
      const { readMyWork } = await import('@/lib/my-work-reader');
      return readMyWork(orgId, new Date());
    }),
    safe(async () => {
      const { listEgressDecisions } = await import('@/lib/egress-policy-store');
      // Reads the recorded decisions themselves (the canonical audit ledger), not the egress POLICY —
      // "what was actually stopped", not "what we say we would stop".
      return listEgressDecisions(orgId, EGRESS_WINDOW);
    }),
    safe(async () => {
      const { computeFinOps } = await import('@/lib/finops');
      return computeFinOps(null, orgId);
    }),
    safe(async () => {
      const { readProvenanceView } = await import('@/lib/provenance-view');
      return readProvenanceView(PROVENANCE_WINDOW, orgId);
    }),
    safe(async () => {
      const { readAuditPage } = await import('@/lib/audit-log-reader');
      return readAuditPage({ page: 1, size: 1 }, orgId);
    }),
    safe(async () => {
      const { computeOrgRoiRollup } = await import('@/lib/roi-reader');
      return computeOrgRoiRollup(orgId);
    }),
  ]);

  const decisions = Array.isArray(egress) ? egress : null;
  // The audit backend reports its own outage in-band, so an unreachable search index must read as
  // "could not ask" rather than as a total of 0 — `readAuditPage` returns an empty page either way.
  const auditTotal = audit && !audit.error && audit.configured ? audit.total : null;

  const input: ProofInput = {
    runsCompleted: runs?.length ?? null,
    casesWaiting: work?.cases.length ?? null,
    egressTotal: decisions?.length ?? null,
    egressProtected: decisions?.filter((d) => PROTECTED.test(d.outcome)).length ?? null,
    // The VERIFIED count, not the total: the claim is "an auditor can re-verify", and a record whose
    // signature no longer checks out is evidence against us, not for us.
    signedRecords: provenance?.verified ?? null,
    auditEvents: auditTotal,
    localShare: typeof finops?.totals.localShare === 'number' ? finops.totals.localShare / 100 : null,
    valueSaved: roi ? money(roi.totals.grossValue) : null,
    aiCost: roi ? money(roi.totals.actualAiCost) : null,
  };

  return NextResponse.json({ points: buildProofPoints(input) });
}

/** How far back the two windowed reads look. Wide enough that a busy tenant is not under-counted. */
const EGRESS_WINDOW = 500;
const PROVENANCE_WINDOW = 500;

/** An outcome that means something was actually withheld — the decisions that make the claim. */
const PROTECTED = /mask|block|redact|deny|refus|anonymi/i;

/**
 * Money in the console's display currency, so ₹ figures group in lakh rather than thousands.
 *
 * The ROI rollup already converts its USD-denominated AI cost at its own boundary (see roi-reader),
 * so this only formats — converting again here would divide the cost a second time.
 */
function money(amount: number): string {
  return formatMoney(amount, DEFAULT_CURRENCY);
}
